### ISSUE TITLE
Make the default avatar in the app gender neutral

### ISSUE THREAD

**Issue by AwareArctic** [acterglobal/a3#1001]
The default avatar in the app (or on the acter.global homeserver?) should be a gender neutral person.

**Comment by gnunicorn** [comment]
Hello @AwareArctic, welcome to the Acter repo. 

> The default avatar in the app (or on the acter.global homeserver?) should be a gender neutral person.

there is no "default avatar" in the app. If there is no avatar set by the user (or loading fails), it falls back to [`multiavatar`](https://pub.dev/packages/multiavatar) using the user-id (including homeserver) as input. 

Do you have issues with your automatically chosen avatar?
