### ISSUE TITLE
Sidesheet title covered by mobile-top-bar

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1029]
Not sure how to detect, but on Android Pixel 6a the top-bar with the camera is covering part of the sidebar titles:

![grafik](https://github.com/acterglobal/a3/assets/40496/629cff1b-6501-49a7-8af3-4b09158ddf42)

**Comment by gtalha07** [comment]
Can confirm the overflow appears on iOS devices too. Attached screenshot latest release on ```iPhone 14 Pro Max```.
![79b8a34a-df81-419c-95a0-8d5a83aea2ea](https://github.com/acterglobal/a3/assets/68579938/df47709b-32eb-4545-9f53-5f4c00eca26d)
