### ISSUE TITLE
When creating chat within space, the space is not always autoselected

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1030]
https://github.com/acterglobal/a3/assets/77483554/88c4fe54-82a0-49f1-a06b-a5a9a046e2b6

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Does this issue is still exist?

if yes then can you help me with the steps to reproduce it as I have checked this in many of the spaces but unable to reproduce.

**Comment by emilvincentz** [comment]
@kumarpalsinh25 no I think this has been fixed. Sometimes it takes a while to load the parent space, but eventually loads.
Will close this issue then:)
