### ISSUE TITLE
Space header is missing when clicking on space avatar in update.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1031]
Space header is missing when clicking on space avatar in update.
Also wierd space widget is shown when clicking on chat avatar.

https://github.com/acterglobal/a3/assets/77483554/4e0b5b54-1194-4c19-b682-59075fec5788

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
I think this issue is now resolved with recent PR requests. Still can you cross check once before we mark this as closed?

**Comment by emilvincentz** [comment]
Yes it's fixed 🙌
