### ISSUE TITLE
space transformed from community can't be displayed

### ISSUE THREAD

**Issue by Simon0Harms** [acterglobal/a3#1037]
Not really important because i think this is a rare case and i only have this space because of nostalgia 

Release:
https://github.com/acterglobal/a3/releases/tag/nightly-2023-10-06
OS: Ubuntu Mate 22.04

I have an old space which was a community before.
It don't has an avatar. When i click on it, i get an error:
![grafik](https://github.com/acterglobal/a3/assets/10880193/4ce183b1-cc0b-4912-9157-487b9e38644a)

Element View:
![grafik](https://github.com/acterglobal/a3/assets/10880193/0befd11c-9d7a-45e5-8e40-edb08002c0ba)

**Comment by gnunicorn** [comment]
This should have been fixed by now. We've replaced the entire way that avatars are handled to be more robust and not generally block the remaining UI if it doesn't load anymore ...
