### ISSUE TITLE
creating Events/Pins in a Space without a avatar leads to error

### ISSUE THREAD

**Issue by Simon0Harms** [acterglobal/a3#1038]
Release:
https://github.com/acterglobal/a3/releases/tag/nightly-2023-10-06
OS: Ubuntu Mate 22.04

It's a space which was i upgraded to an acter space
But the error occurs when you create an acter space without an avater, too.
![grafik](https://github.com/acterglobal/a3/assets/10880193/5722e765-80a5-47f8-ac40-225e6d6ae058)

It's just this error message, you can created the pin/event without a problem

**Comment by gnunicorn** [comment]
@Simon0Harms is that still present in the latest release?

**Comment by gnunicorn** [comment]
This is fixed now.
