### ISSUE TITLE
App wont start on MacOS

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1042]
this morning when i opened the app, it wouldt open.
i tried download the latest nightly, but that didnt fix it.

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/80b98c8e-45aa-4d89-a4b4-6aebedf8177e)
![Image](https://github.com/acterglobal/a3/assets/77483554/606dde98-42ee-4505-be30-6e0c166cdc0c)

**Comment by emilvincentz** [comment]
Full report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: C1DE25F8-E252-47F6-BEC6-882655E900FD
CrashReporter Key:   121CF117-3C48-19FA-1511-5F6D5D45CF63
Hardware Model:      MacBookPro15,2
Process:             Acter [50178]
Path:                /private/var/folders/*/Acter.app/Contents/MacOS/Acter
Identifier:          global.acter.a3
Version:             0.0.1 (1)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           global.acter.a3 [26368]

Date/Time:           2023-10-11 09:47:56.7914 +0200
Launch Time:         2023-10-11 09:47:56.7754 +0200
OS Version:          macOS 13.4 (22F66)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 1 Taskgated Invalid Signature

Triggered by Thread:  0

Thread 0 Crashed:
0   ???                           	       0x11c6b1070 _dyld_start + 0
1   ???                           	               0x1 ???


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b0defb50
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011c6b1070  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0


Binary Images:
       0x11c6ac000 -        0x11c747fff ??? (*) <9e98a840-a3ac-31c1-ab97-829af9bd6864> ???
       0x10f110000 -        0x10f113fff  (*) <afdb12df-cd95-3516-baed-81b65f7853c5> ???
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Acter","timestamp":"2023-10-11 09:47:56.00 +0200","app_version":"0.0.1","slice_uuid":"afdb12df-cd95-3516-baed-81b65f7853c5","build_version":"1","platform":0,"bundleID":"global.acter.a3","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4 (22F66)","roots_installed":0,"name":"Acter","incident_id":"C1DE25F8-E252-47F6-BEC6-882655E900FD"}
{
  "uptime" : 360000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,2",
  "coalitionID" : 26368,
  "osVersion" : {
    "train" : "macOS 13.4",
    "build" : "22F66",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-11 09:47:56.7914 +0200",
  "incident" : "C1DE25F8-E252-47F6-BEC6-882655E900FD",
  "pid" : 50178,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-11 09:47:56.7754 +0200",
  "procStartAbsTime" : 361289532361685,
  "procExitAbsTime" : 361289548052922,
  "procName" : "Acter",
  "procPath" : "\/private\/var\/folders\/*\/Acter.app\/Contents\/MacOS\/Acter",
  "bundleInfo" : {"CFBundleShortVersionString":"0.0.1","CFBundleVersion":"1","CFBundleIdentifier":"global.acter.a3"},
  "storeInfo" : {"deviceIdentifierForVendor":"FDEC44C1-F1AB-508E-964C-19A0BEC9BCBE","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "global.acter.a3",
  "crashReporterKey" : "121CF117-3C48-19FA-1511-5F6D5D45CF63",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 16777216,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1026,
  "bridgeVersion" : {"build":"20P5058","train":"7.5"},
  "sleepWakeUUID" : "5360DE3F-0497-4865-9312-C0C4BBCEAE34",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":1,"namespace":"CODESIGNING","indicator":"Taskgated Invalid Signature"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":4288184,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4771745904,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701801053008},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":20592,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":1,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 638976,
    "arch" : "x86_64",
    "source" : "P",
    "base" : 4771725312,
    "uuid" : "9e98a840-a3ac-31c1-ab97-829af9bd6864"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4547739648,
    "size" : 16384,
    "uuid" : "afdb12df-cd95-3516-baed-81b65f7853c5",
    "name" : ""
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1004K resident=0K(0%) swapped_out_or_unallocated=1004K(100%)\nWritable regions: Total=8192K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8192K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          4K        1 \n__DATA                              32K        2 \n__DATA_CONST                        48K        2 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         368K        3 \n__TEXT                             640K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                             65.1M       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "5275dc35c71a7b8e8e0f584446053351c9987366",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "64d14f3e1008ca2fac17a163"
      },
      "deploymentId" : 240000064
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro15,2, BootROM 1968.120.12.0.0 (iBridge: 20.16.5058.0.0,0), 4 processors, Quad-Core Intel Core i5, 2,3 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics 655, Intel Iris Plus Graphics 655, Built-In
Display: DELL P2721Q, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, Micron, MT52L1G32D4PG-093
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, Micron, MT52L1G32D4PG-093
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Dec  9 2022 16:56:24 version 9.30.492.0.32.5.87 FWID 01-3a11ec19
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: iPhone 2, Ethernet, en7
USB Device: USB31Bus
USB Device: iPhone
USB Device: hub_device
USB Device: composite_device
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

**Comment by gnunicorn** [comment]
I am messing with the certificates in the hope to get the push-notification things working ... this seems to have caused this unintended side-effect :( .
