### ISSUE TITLE
Space calendar events API should filter into upcoming and past events.

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#1046]
Currently space calendar events shows all events (upcoming and past).
<img width="1465" alt="Screenshot 2023-10-16 at 2 56 12 PM" src="https://github.com/acterglobal/a3/assets/68579938/a89f1d31-7514-40e3-b57b-c399b7e8f4c2">

**Comment by gnunicorn** [comment]
On the overview we probably only want to show on-going and upcoming events: anything with `EndTime < CurrentTime`, potentially highlight _ongoing_ even further on the top. In the event-section we probably want to do a similar thing, too. Maybe even keep the past-events out of the view until a filter-change triggers them to be included?

**Comment by gtalha07** [comment]
> On the overview we probably only want to show on-going and upcoming events: anything with `EndTime < CurrentTime`, potentially highlight _ongoing_ even further on the top. In the event-section we probably want to do a similar thing, too. Maybe even keep the past-events out of the view until a filter-change triggers them to be included?

We could do expand/collapse view with the past events.
