### ISSUE TITLE
When clicking on the space avatar in a chat icon, it opens a wierd space within the chat.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1048]
https://github.com/acterglobal/a3/assets/77483554/6c5f9aaf-8491-4b3d-b093-39c394503587

**Comment by kumarpalsinh25** [comment]
Is this issue is generated in specific use-case? May I know steps to reproduce it?

I have checked it with the same scenario and it is working fine. Attaching screen recoding for the reference.

https://github.com/acterglobal/a3/assets/51526480/cdb6c238-7baa-4e08-a5aa-f7467f5bd42c

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Oh, I see. My Bad.
Thanks for the details.
