### ISSUE TITLE
remove matrix preview link when someone is mentioned

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1052]
takes up a lot of space

![Image](https://github.com/acterglobal/a3/assets/77483554/f3bc5b1b-b812-46cb-aca5-fb7603a366a6)

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
CC : @gnunicorn 

This is issue is user specific issue. 

We are already code hiding Preview Link for mentioned message in [text_message_builder.dart](https://github.com/acterglobal/a3/blob/main/app/lib/features/chat/widgets/text_message_builder.dart) as below.

```
final urlRegexp = RegExp(
      r'https://matrix\.to/#/@[A-Za-z0-9]+:[A-Za-z0-9]+\.[A-Za-z0-9]+',
      caseSensitive: false,
    );
```

However above RegExp not working for "@emil-oceankan-exmpl:acter.global" as this username contains "-" in the name.

I have updated Reg as below and it started working.

 ```
final urlRegexp = RegExp(
      r'https://matrix\.to/#/@[A-Za-z0-9\-]+:[A-Za-z0-9\-]+\.[A-Za-z0-9\-]+',
      caseSensitive: false,
    );
```

Code will be merged to main in upcoming PRs.
