### ISSUE TITLE
Improve performance when scrolling chats

### ISSUE THREAD

**Issue by Bargsteen** [acterglobal/a3#1057]
### Feature Request
Scrolling in the chat is a bit slow and does not feel as smooth as scrolling for example text messages.
I've tried to capture it in a screen recording, but it is subtle. Especially when you can't see the location of my finger.

### Steps to reproduce
1. Open Acter
2. Navigate to the **Chat** section
3. Open a chat, for example **Acter Foyer**
4. Scroll up and down in long and short bursts

#### Expected
Scrolls as smoothly as text messages or similar.

#### Actual
Scrolls slower than the finger and is a bit laggy at times.

https://github.com/acterglobal/a3/assets/5469652/32b6ecdf-8f8d-430c-b768-6683e325546c

### Versions
- Acter App: 1.23.1012/iOS
- Device: iPhone 11 Pro

**Comment by gnunicorn** [comment]
Maybe unrelated, but scrolling a larger room I got these earlier today:
![grafik](https://github.com/acterglobal/a3/assets/40496/f1224cf7-a011-42b3-acf0-1dcb74e61d38)

**Comment by gnunicorn** [comment]
@kumarpalsinh25 I don't know. that's all it showed me.

**Comment by Bargsteen** [comment]
Hi @gnunicorn, I just tried it again on 1.24.2208, and all my chats are still laggy when scrolling.
It seems like I don't have the rights to reopen this issue.
Let me know if you need more information from me on this.

**Comment by gnunicorn** [comment]
thanks @Bargsteen, I re-opened the issue. Could you do me a favor, scroll around and the [send an app internal bug report](https://docs.acter.global/s/handbook/doc/reporting-a-bug-with-the-internal-bug-reporter-9i7rz8pfbh) with the logs included? And note the issue number the success message shows you and post it here, please :pray: ?!?

**Comment by Bargsteen** [comment]
@gnunicorn Sure thing, I just did that, but I did not get any success message upon sending the bug report (perhaps a separate bug ;)). I wrote "laggy scroll in chat" in both of the reports I've sent, so hopefully you can search for it.

**Comment by gnunicorn** [comment]
for the record the logs are in https://github.com/acterglobal/a3-meta/issues/88 and https://github.com/acterglobal/a3-meta/issues/89

**Comment by emilvincentz** [comment]
still seeing this problem:

https://github.com/acterglobal/a3/assets/77483554/2f1d5c5e-a7e7-4656-8d95-22e414658b2b

**Comment by gnunicorn** [comment]
fixed in latest release.
