### ISSUE TITLE
Enable user highligh text (so that one can copy the text)

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1074]

**Comment by kumarpalsinh25** [comment]
Hello @emilvincentz @gnunicorn @gtalha07 

![Image](https://github.com/acterglobal/a3/assets/51526480/3ad583c5-498b-464e-bb57-bf5b3fcf1a66)


For this point, instead of provide hightligt text, can provide provide copy option button like WhatsApp, Telegram and other apps are doing?

Because Highlight Text is ideal option for Web Apps. For mobile and desktop app, generally copy button is more relevant.

Please share your thoughts.

**Comment by emilvincentz** [comment]
hi @kumarpalsinh25 
I think this is the updated design. 
Is that you mean?
https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=7354-56908&mode=design&t=bsdGVTonhxasuCAV-4

<img width="475" alt="Screenshot 2023-10-24 at 16 39 31" src="https://github.com/acterglobal/a3/assets/77483554/f398368e-40ba-4d77-b62b-d5ee85f14f00">

**Comment by kumarpalsinh25** [comment]
Yes @emilvincentz,
This is exactly what I mean.

**Comment by gnunicorn** [comment]
has been fixed in #1591
