### ISSUE TITLE
When/where to make opt-in screen for notifications

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1084]
How/when/where do we want to get the user to consent for notifications?
What we want to take into considerations is both:

- UX
- Requirement/Restrictions from app stores.
- Implementation

**Comment by emilvincentz** [comment]
How/when/where do we want to get the user to consent for notifications?

**Comment by gnunicorn** [comment]
Pointing to the [apple developer docs](https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications), which recommend to _not_ just do it at startup but at a place with more context. Maybe when the person navigated to the chat-section for the first time? Or after having send their first message in a chat?
