### ISSUE TITLE
Issues with loading content

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1086]
Note sure what exactly is happening, but sometimes experience problems with loading. 
Loading both avatars, sub-spaces and members. 

It doesnt really happen persistent.

And yes, I have good internet connection:)

https://github.com/acterglobal/a3/assets/77483554/4e156c16-2269-47ff-9134-1706dafa73a4

**Comment by emilvincentz** [comment]
One of our users has the same problem:


![Image](https://github.com/acterglobal/a3/assets/77483554/d3599249-a4fe-40f9-bc25-60996cbc4dad)
![Image](https://github.com/acterglobal/a3/assets/77483554/7e7fd60f-1312-464f-b2bb-6e3af00417c4)
![Image](https://github.com/acterglobal/a3/assets/77483554/b3951b45-baab-4649-b82f-96adeedbd817)

**Comment by emilvincentz** [comment]
https://github.com/acterglobal/a3/assets/77483554/d00b29be-cb88-42c3-94ed-6931559be08d

Maybe linked to this as well. 
I made a fix, by restarting the app

**Comment by emilvincentz** [comment]
User reported this:
When clicking on push notificatinos, its stuck on loading.
After reopning the app it no longer loads, but the message can not be de-crypted. Says "re-request session keys".


![Image](https://github.com/acterglobal/a3/assets/77483554/b74733bb-a694-4dd3-b947-cdda8862593f)


![Image](https://github.com/acterglobal/a3/assets/77483554/e0485040-0121-4e3a-bd30-c169ea48b7a2)

**Comment by emilvincentz** [comment]
not loading chat avatar in space chats (only the ones i havent joined)


![Image](https://github.com/acterglobal/a3/assets/77483554/ce9bd7b8-2d1b-4885-a9e0-58b92fd2593a)

**Comment by gnunicorn** [comment]
Let's investigate what is going on the wire, eg. with https://proxyman.io/

**Comment by kumarpalsinh25** [comment]
@gnunicorn @bitfriend 
Is there anything we did on recently deployed new server?
Because this loading issue frequency is reduce and not able to regenerate very often.

**Comment by emilvincentz** [comment]
Not as frequent, but still experienced it this morning ![image](https://github.com/acterglobal/a3/assets/77483554/c6ae7528-475e-4b37-ab43-794e50875943)

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Yes true, issue is still exist. But it is not as frequent as it was previously. There are few network calls getting timeout which leads to this issue.

**Comment by gnunicorn** [comment]
we want to try by increasing the internal matrix-sdk timeout. see https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/config/struct.RequestConfig.html#method.timeout

**Comment by kumarpalsinh25** [comment]
@gtalha07 
Here is the list of the other related issues to this[ Issues with loading content #1086](https://github.com/acterglobal/a3/issues/1086):
- #1107 
- #1142 
- #1206 
- #1235

**Comment by gnunicorn** [comment]
Seeing this with a fresh login using emilio:



![Image](https://github.com/acterglobal/a3/assets/40496/44aa339a-fa89-437e-8f59-f44a3cd6cfe2)
![Image](https://github.com/acterglobal/a3/assets/40496/390ebd49-25d6-40a7-ab20-3d67356cafd5)
![Image](https://github.com/acterglobal/a3/assets/40496/5f64120e-6b0b-4195-b7e4-398196e31e43)
![Image](https://github.com/acterglobal/a3/assets/40496/9e595b3d-ac66-46dd-a26f-ae3d2cdf841b)
![Image](https://github.com/acterglobal/a3/assets/40496/70022318-fb76-4a95-8c0a-b73a89beeeb1)
![Image](https://github.com/acterglobal/a3/assets/40496/a146f5ac-486f-4f57-988a-8bbd13f53728)

**Comment by gnunicorn** [comment]
of course I can't reproduce it anymore now. @kumarpalsinh25 can you still reproduce this? Could you try to take a look at the connections going in & out and if there is anything weird, after applying https://github.com/acterglobal/a3/pull/1277 ?

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
There are few loading issues I faced. Sharing videos for reference which shows logs from proxyman.
https://github.com/acterglobal/a3/assets/51526480/1e95eb4f-9e4f-4eb8-83b2-c282ede5ecec

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
One more use-cases, sometime there were no loading failed issue but can see some APIs failure.

- Reference Video:
https://github.com/acterglobal/a3/assets/51526480/c4ccf64f-96aa-49d3-b4b0-6546e40cf567

**Comment by gnunicorn** [comment]
> There are few loading issues I faced. Sharing videos for reference which shows logs from proxyman.

room entering doesn't lead to a remote call at first but just an attempt to load the room locally. The error indicates the inner SDK doesn't know about that room. Weird that it showed up in the first place ...

The second video shows the same circumstance. Let's put that into a separate issue, because showing a room that is then not found (regardless of whether it is a space or chat) is not related to the other "content doesn't load" issues but has a separate code path.

Key-upload failure, too, isn't relevant for our problem. That is a background process without any repercussions if it failed.

**Comment by gnunicorn** [comment]
What is weird is that even though I could experience it almost every time and so you reported this, once we through the proxy in between the loading issues seems to have disappeared ... incidicating that this might be related to the way the HTTP requests are handled by either the client or the server.

I did suspect HTTP/1.1 polling already before ... it could stall any number of requests on the same connection if one request took a very long time ... but I though we had like 20 or so concurrent connections in our pool....

**Comment by gnunicorn** [comment]
also seeing that sometimes new updates do not appear (at all).
