### ISSUE TITLE
app chrashes when trying to type user in DM creation on IOS

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1091]
Ive managed to create dm group chat before. Howeve now when i try it keeps chrashing .

https://github.com/acterglobal/a3/assets/77483554/61346a0e-dc06-4d06-9fac-8fdd5f7db33f

**Comment by emilvincentz** [comment]
interestingly enough, element seem to chrash as well, but without any pattern.
not sure if there is a connection


https://github.com/acterglobal/a3/assets/77483554/18439aa5-ae06-44d4-ab92-1ab6d119e0e1

**Comment by gnunicorn** [comment]
@emilvincentz which version is that?

**Comment by emilvincentz** [comment]
@gnunicorn nightly-2023-10-27

**Comment by emilvincentz** [comment]
Now it currently is working again, but not sure what either causes  or fixed it.

**Comment by gtalha07** [comment]
> Now it currently is working again, but not sure what either causes or fixed it.

It seems there's insufficient evidence as to what happens to be the crash reason. I haven't experienced this on my side (Tested on iPhone 14 Pro Max). I would suggest de-prioritise it and take care of other issues.

**Comment by emilvincentz** [comment]
Sounds good @gtalha07

**Comment by emilvincentz** [comment]
just experienced again, but after restarting the app it works again. However this time i got this bug: #1130

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue is still persists? Can you check and confirm?

**Comment by emilvincentz** [comment]
hmm no seems resolved:)
