### ISSUE TITLE
No indicator showing the notification setting i have selected

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1093]
Should show the setting that is selected.

![Image](https://github.com/acterglobal/a3/assets/77483554/008ad3d8-8f96-48f5-afec-8767398a5c3e)

**Comment by emilvincentz** [comment]
I see this was closed 2 weeks ago, but still doesnt see it in the app (i have the latset nightly from 4th nov) 
Has it been merged yet? @kumarpalsinh25 @gnunicorn

**Comment by kumarpalsinh25** [comment]
@emilvincentz
Indicator management for the selected notification setting is there but I think there is issue when 'Default' option is selected. I will cross details and update you. Meantime can you cross check with other notifications like 'muted', 'mentions' etc

**Comment by emilvincentz** [comment]
ah yes, thats the case @kumarpalsinh25. It's not showing when "default". Thanks for clarifying

**Comment by kumarpalsinh25** [comment]
I will cross check the details and do the needful.

**Comment by kumarpalsinh25** [comment]
@bitfriend 
When we set default notification mode, there are some issues.

[acter_flutter_sdk_ffi.dart](https://github.com/acterglobal/a3/blob/fd3dacaf25f449bc44780da3002948f83d26ada5/app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart#L34685)
```
 /// set the RoomNotificationMode
  Future<bool> setNotificationMode(
    String? newMode,
  ) 
```

Currently `null` is passed on above method when user set default notification but it look like it is not updating relevant changes.

**Comment by emilvincentz** [comment]
i think this has been resolved. So closing
