### ISSUE TITLE
DM creation: not able to scroll down to select user user (IOS)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1095]
When searching for users, its not possible to scroll on the list.

https://github.com/acterglobal/a3/assets/77483554/2166ac30-874f-4a70-8f6c-48baaee19794

**Comment by gtalha07** [comment]
@emilvincentz  It seems like the scrolling works fine here, the keyboard is obscuring the list view which can be dismissed and you can see full scroll effect...

**Comment by gtalha07** [comment]
I think we the viable fix for showing full scroll view is to hide the keyboard when the user goes through the user list.

**Comment by emilvincentz** [comment]
Ah yes, seems to work now - how funny. But never the less great:)

**Comment by emilvincentz** [comment]
Will close this issue then
