### ISSUE TITLE
Subspaces and chat does not show in the space overview

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1096]
https://github.com/acterglobal/a3/assets/77483554/e941c04b-7119-44ac-bd59-71d85c0490fc

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue is generated in specific use-case? 
I have checked couple of spaces where I can see chats and sub-spaces on overview page.

**Comment by emilvincentz** [comment]
hey @kumarpalsinh25 yes, I have invited you to the "Beacon" space. thats where the above currently happens.

**Comment by kumarpalsinh25** [comment]
I have accepted invitation of the "Beacon" space. However I'm not able to see any chats and sub-spaces anywhere not just overview.



![Image](https://github.com/acterglobal/a3/assets/51526480/2c0a9f85-ea9b-4697-b2c6-ed2e888fbb2d)



![Image](https://github.com/acterglobal/a3/assets/51526480/59b90d70-06c3-4e63-9901-753c63bb0eba)


I have also cross checked element for this but got able to see any  chats and sub-spaces over there also.


![Image](https://github.com/acterglobal/a3/assets/51526480/be49e2e7-da9b-4986-8c35-6f04390377b5)

**Comment by kumarpalsinh25** [comment]
hmm.. Strange! 
Is there any other spaces where we can reproduce the issue?

**Comment by emilvincentz** [comment]
Strange indeed. I havent come across others  yet.

**Comment by gnunicorn** [comment]
_sigh_ ... the way that the space tree is flatten per user is pretty ... messy ... and the implementations are unclear ...

I _suspect_ the server isn't showing @kumarpalsinh25 these rooms in the [hierarchy response]( https://spec.matrix.org/v1.8/client-server-api/#get_matrixclientv1roomsroomidhierarchy) it calculates as he wouldn't be able to access them - could it be that the rooms are "private" in visibility and _invite_only_ in invite mode? Then the server, it appears, filters them out of the response.

There is some more ugliness in there, as to even when it is a room you _could_ join, if you had been part of it and left it, the query also doesn't show it anymore. It is pretty mad.

**Comment by emilvincentz** [comment]
@gnunicorn Well I havent joined any of the rooms or subspaces, but can still see them, so I expect that they are not invite only 
<img width="475" alt="Screenshot 2023-10-31 at 12 13 44" src="https://github.com/acterglobal/a3/assets/77483554/4308b7c1-3640-45e7-a85d-09f3214fa7bc">
<img width="474" alt="Screenshot 2023-10-31 at 12 14 08" src="https://github.com/acterglobal/a3/assets/77483554/d0ea429e-5f71-400a-aa7a-6e9e8363ffd1">

**Comment by emilvincentz** [comment]
I have have now joined one of the subspaces and also invited you (south toe river...)

**Comment by gnunicorn** [comment]
I, too, can see them in both Element and Acter...

![Screenshot_20231031-120119](https://github.com/acterglobal/a3/assets/40496/5e1d1b2c-689e-43f9-b82f-4dd9a738c42d)
![Screenshot_20231031-120112](https://github.com/acterglobal/a3/assets/40496/1c8f63da-c135-40d3-83b5-7cf8236d92fc)
![Bildschirmfoto_2023-10-31_11-59-28](https://github.com/acterglobal/a3/assets/40496/cc9f22d4-b6b4-4e11-8c09-b7be817f9cb4)

@kumarpalsinh25 try restarting acter?

**Comment by kumarpalsinh25** [comment]
Now I can see one subspace name "The South Toe River Valley" and it is showing on both Element as well as Acter.

![Screenshot 2023-10-31 at 5 40 12 PM](https://github.com/acterglobal/a3/assets/51526480/ce8ddb7c-d303-4087-aee5-d9095622bbe9)

**Comment by emilvincentz** [comment]
hmm, but funny how you Kumar still dont see the other sub-spaces and chats .

**Comment by gnunicorn** [comment]
odd... but honestly, that room_hierarchy API is freaking broken...

**Comment by kumarpalsinh25** [comment]
This is really strange however I'm able to see subspace in the overview section whatever is showing in detail page (With reference to orignal issue point discussion )

**Comment by gnunicorn** [comment]
ideally if the user isn't part of any subspace, we want to see if there are any other sub spaces and show them in the overview-chat-widget. Unfortunately, this isn't technically trivial and requires server requests ...

needs product def what to show under which conditions...
