### ISSUE TITLE
Roomid doesnt work when shared (its not clickable and also does not redirect to the chat)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1097]

**Comment by gnunicorn** [comment]
Can you be a bit more precise where you are when you try to click it?

**Comment by emilvincentz** [comment]
https://github.com/acterglobal/a3/assets/77483554/b8425c2e-1287-4913-baf0-7aa4bbf1e850

@gnunicorn

**Comment by gnunicorn** [comment]
we should share the matrix-id-link rather than the ID and add support for clicking matrix-ids and show room previews.
