### ISSUE TITLE
MacOS app sometime starts to flicker

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1100]
Dont know what triggers it, but sometimes the apps starts to flicker. 
Its tempoarly fixed when closing and reopening the app

**Comment by emilvincentz** [comment]
https://github.com/acterglobal/a3/assets/77483554/1c9e6cc8-f03b-4ae1-9399-c645dc5998cb

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue is still persists? Can you check and confirm?

**Comment by emilvincentz** [comment]
no longer persists, so will close this issue:)
