### ISSUE TITLE
Replace is_dm() with is_direct()

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#1105]
`is_direct()` is async func and it can't be used in error case of `chatAvatarUI()`.
So we have to keep both `is_dm()` and `is_direct()` if we want to replace `is_dm()` with `is_direct()`.
![image](https://github.com/acterglobal/a3/assets/48786056/57b8b2f0-3ed0-4af6-965d-801eba97281d)

**Comment by gnunicorn** [comment]
@bitfriend mind sharing the recommended code from the rust-team!?!

**Comment by bitfriend** [comment]
I think it is hard to avoid async fn because `is_direct()` fetches result from remote server.

**Comment by bitfriend** [comment]
I guess it needn't to detect whether this room is dm or not on failure.
If it is okay, we can remove `is_dm()` api and keep only `is_direct()` api.

**Comment by gnunicorn** [comment]
fixed by #1471
