### ISSUE TITLE
Stuck on loading when inviting user to chat

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1107]
I wanted to invite a user to a chat, but it was stuck on loading.
However later on if figured out it prob was because she was already in the chat.
Ideally we want to show a message that the user has alreayd joined, instead of endless loading

(update 8th Novemember)
It unfortunately also seems to happen although the user is not in the room.
What happens:
I click "create chat". -> I type user name in search field -> the search result list is stuck on loading -> if i wait long enough, below image shows.

I reopen the app several times -> works again.

![Image](https://github.com/acterglobal/a3/assets/77483554/17a79674-e5b8-4b3b-bd9c-c153e519f05d)

**Comment by emilvincentz** [comment]
It unfortunately also seems to happen although the user is not in the room.
What happens:
I click "create chat". -> I type user name in search field -> the search result list is stuck on loading. 

I reopen the app several times -> works again.

**Comment by gnunicorn** [comment]
we still occasionally see timeout issues coming from the server but with the reduced number of requests we are sending, this has gotten a lot better. is this still occurring?

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue is still there?

**Comment by emilvincentz** [comment]
I think it's solved. closing the issue

**Comment by gnunicorn** [comment]
There is still a problem with this screen if the user is already in the room or has already been invited it still spins Forever

**Comment by emilvincentz** [comment]
this is also the case for spaces.
In this case, i had made a superinvite that should have added the member to the space. For some of the spaces added to the invite code, he joined, but others he didnt joined. invite code: gpkenya04

when i then tried to "manually" invite him to the space, it was stuck on loading.

https://github.com/acterglobal/a3/assets/77483554/5c3a47e0-bd1a-4eba-bcdb-d23ab2dfdfdf

**Comment by gnunicorn** [comment]
yeah, it's the same dialog.

**Comment by gtalha07** [comment]
@emilvincentz I have a working solution to this fix, that strips off room members from found users (they won't appear up in list). Would that be viable or do we still want to show room members in invite user list but put information that they already joined???

**Comment by emilvincentz** [comment]
@gtalha07 yes ideally we want to show room members, but that they've already joined. As I see some cases where people won't know that they have joined, so they search for them, but then dont understand why they dont come up in the results.

**Comment by emilvincentz** [comment]
@gtalha07 this is still happening, but i guess its because the above has not been merged yet? that should fix it right?

Concretely it happens, when i type username and then scroll.


https://github.com/acterglobal/a3/assets/77483554/ade9d79a-2a72-49b1-b562-bdcec4c05908

**Comment by gtalha07** [comment]
> @gtalha07 this is still happening, but i guess its because the above has not been merged yet? that should fix it right?
> 
> Concretely it happens, when i type username and then scroll.
> 
>  IMG_0476.MOV

Yes, its merged just as of now. The invite button will show joined/invited state instead of just non-interactive button as shown.
