### ISSUE TITLE
Bug in redacting pins/updates/event

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1109]
Although you redact/delete a pin/update it still shows. 
Event when restartin the app it still shows. However usually an undefinite time, they go away.

**Comment by kumarpalsinh25** [comment]
@bitfriend 
Can you check for below method regarding this issue? It is giving success response for pin and/or event reduction but it is not actually deleted.

```
 /// redact an event from this room
  /// reason - The reason for the event being reported (optional).
  Future<bool> redactContent(
    String eventId,
    String? reason,
  )
```

**Comment by gnunicorn** [comment]
the internal state machine for our objects doesn't yet support redacting ... same as it doesn't remove items that are part of a specific space if you left it ... we should probably make some tracking issue for these somewhere...

**Comment by gnunicorn** [comment]
fixed in https://github.com/acterglobal/a3/pull/1448 .
