### ISSUE TITLE
Show suggested users when adding  people to chat/space

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1110]
Feedback from users:

_"It would be great if already established connections would show up faster in searches. For example, when I search for just "jo" nothing comes up until I had the : which I think will confuse folks and take a lot of explaining
this is while trying to add her to a chat channel in one of our spaces"_

**Comment by gnunicorn** [comment]
fixed in https://github.com/acterglobal/a3/pull/2156
