### ISSUE TITLE
Uploading image to update on IOS is broken

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1119]
https://github.com/acterglobal/a3/assets/77483554/a1e72f78-af70-47c5-817d-33177fa87e19

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue is still persists? Can you check and confirm?

- Tested on iPhone 12 with iOS 17.1 and it is working fine.

**Comment by emilvincentz** [comment]
Yes still doesn't work for me (iPhone de 3rd gen) 
Will try to test on some other iPhones as well

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
I'm able to reproduce this issue. 

It is working fine with debug mode but when I have installed latest release app from TestFlight then over there I faced this issue. This is strange behaviour but will check details and do the needful.
