### ISSUE TITLE
should parent spaces not figure in the overview section of space under "Related spaces"?

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1120]

**Comment by gnunicorn** [comment]
can you make a screenshot what you mean?

**Comment by emilvincentz** [comment]
@gnunicorn 
This is an example where there are multiple sub spaces under WeRise, eg. "Freedom Unleashed..."
However We Rise doesnt figure under "related spaces".

![Uploading IMG
![IMG_9598](https://github.com/acterglobal/a3/assets/77483554/506574fb-3b03-4c6f-b608-1afb53a1a84f)
_9599.PNG…]()

**Comment by gnunicorn** [comment]
Sure, if you think it matters. I mean, it is clearly in the top icon, especially if you  have more than one other related space, showing the parent there (again) is a bit of pointless repetition. Maybe we can come to a rule of _showing_ the parent if there aren't any _related spaces_ found? So show one or the either?

**Comment by emilvincentz** [comment]
I think thats a great rule. So:
If there are subspaces, but no parent spaces = show sub spaces under "related spaces in the overview"
If there are no subspaces, but only parent spaces = show parent spaces under "related spaces in the overview"
If there are both subspaces and parent spaces = only show sub spaces under "related spaces in the overview"

Right?

**Comment by gnunicorn** [comment]
I was going for a simpler: if there aren't any other related spaces ( / children), show at the least the parent if given.

The related sub and recommended spaces is a bit of a technically complex part - because there can be server-side pagination and stuff - I'd like to avoid putting all the complexity from the page into this widget as well ...

**Comment by gnunicorn** [comment]
fixed with #1506
