### ISSUE TITLE
Fix/improve user path

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1121]
**Chats**
Currently if a user go to "Space A" and then to the spaces page and click on a Sub space (Space B), when the user then click on the back button, the user is sent back to the home page. 

Instead, the user should be directed back to the previous page. In this example it means, that when the user click on the back button from Space B, the user should be directed back to Space A.

**Chats**
The same should be for chats, meaning if a user click and enter a chat from a space and the user click on the back button, the user should be directed back to the space, not the chat overview. The user only be directed back to the chat overview, if the user entered the chat from the chat overview.

**Comment by gnunicorn** [comment]
This is due to us having to use context.go rather than than push to get around the routing issue (of then the outer side not properly updating). refs #955

**Comment by kumarpalsinh25** [comment]
@Good night!unicorn 
CC: @emilvincentz 

I think this is issue is resolved with #955 but there are few use-case are different specific to back navigation. If current implemented on latest build is good then we can close this issue.

**Comment by emilvincentz** [comment]
Yes, for chat was fixed 🙌but still need the navigation from a sub-space back to the parent soace as well, as described in this issue

**Comment by gnunicorn** [comment]
I am not sure, what you are referring to. Other than that
> Instead, the user should be directed back to the previous page. In this example it means, that when the user click on the back button from Space B, the user should be directed back to Space A.

previously a user would create a pretty large stack of pages to go back and back and back from and that - with the previous shell-route - `push` wasn't feasible/possible to navigate from space to space (it would only replace partial views). 

However, with the new stateful-shell-route and tab-again-for-root, I don't think the stack is still a concern. Let's replace the `goNamed` of space to space with a `pushNamed`!

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Understood, will do the needful here.
