### ISSUE TITLE
Multi-parent space avatar support for space and chats

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1122]
Now that a user  can link/unlink spaces and chats, we also need to update the avatars.
E.g.
- Unlinking a chat from one space and linking to another space, should also update the avatar to the corresponding space logo.
- Linking a chat/space to multiple spaces, should also reflect in the UI (see designs from design team)

![Image](https://github.com/acterglobal/a3/assets/77483554/3a8ade82-ea8a-48cf-8662-3c59966b2f7b)

**Comment by emilvincentz** [comment]
Also applies to dialogie boxes, eg. when selecting spaces/chats to link, and also when creating super invites.

**Comment by emilvincentz** [comment]
@kokodavid can you add the designs for this flow? 
- The avatars, but also the designs that shows the connected spaces of a chat?

**Comment by gnunicorn** [comment]
@kokodavid can you post the figma link here pls?

**Comment by kumarpalsinh25** [comment]
@gtalha07 
Can we close this point if it is done?
