### ISSUE TITLE
Onboarding Screens overflow issues

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1124]
The pre-login onboarding screens are not responsive and have some bad overflow issues (even though there is no content hidden):
![image](https://github.com/acterglobal/a3/assets/40496/00f4ec81-2b75-4def-86f4-3dfb820270c4)
![image](https://github.com/acterglobal/a3/assets/40496/1ac55fee-f215-4e99-8297-9881a8ea3218)
![image](https://github.com/acterglobal/a3/assets/40496/bf71ae1d-0709-43a4-94a4-017ebc389b72)

**Comment by kokodavid** [comment]
@gnunicorn I am trying to fix the font issue , the font size on android is very small and not well visible . Any Ideas on why they become smaller on Android while they are visible on Desktop ?

**Comment by gnunicorn** [comment]
@kokodavid  in an attempt to fix an overflow issue on the bottom, I did switch it to a scaling font widget, but it appears that for some reason it doesn't reliably do the right thing :( ...

**Comment by kokodavid** [comment]
@gnunicorn Alright , I'll raise a PR with the fixes and then you can reverse on the font fix.
