### ISSUE TITLE
scrolling issue on iOS (linking existing chat)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1127]
this only happens when linking chat, not linking space

https://github.com/acterglobal/a3/assets/77483554/7b246a53-549e-4d81-b2a9-c1894865cfc4

**Comment by emilvincentz** [comment]
@kumarpalsinh25 here you go ;)

i also had an issue with the search field not working, but now seems to work again:)

**Comment by emilvincentz** [comment]
The same thing happens on viweving the sub spaces, so might not only be linked to chat.


https://github.com/acterglobal/a3/assets/77483554/da0a8d51-49c0-465c-bda8-92445c99c2cd

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
This looks different issue than the 'Scroll issue on linking existing chat'. Can you create separate ticket for it and assigned it to me?
