### ISSUE TITLE
fixes for events

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1128]
More important
- [x] #1433 
- [x] Remove "space" between hour and minute scroll (currently when you scroll to set a time, you can only scroll  if you press and scroll e.g. on the number 5 or 6, but if you scroll on the "space" between 5 and 6, you cant scroll.
- [x] Auto select end-date to be 1 hour after the start time. 
(Currently When creating event, the date and time picker Is making troubles. When adding a day and start time, without also jumping to end date, it says error.)
- [ ] #1475
- [x] #1473
- [x] Show the spaces that an event is nested under

less important
- [x] Make minute selector to 5 min intervals, insted 1 minute invervals.
- [x] #1474
- [x] Can we make another time picker solution for desktop? its really hard with the scroll

**Comment by emilvincentz** [comment]
there are two other things I see:
1. Events are not displayed in chronological order
2. Also we need somehow differ between past and upcoming events

**Comment by gnunicorn** [comment]
only one left in this tracking issue and it has its own issue, closing as mostly done.
