### ISSUE TITLE
DM chat creation stall indefinitely.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1130]
When i create DM, its stuck on loading. 
However on element i can see that the DM has been succefully created. 

https://github.com/acterglobal/a3/assets/77483554/41548ce4-c071-40e6-bb4a-24f9215258a7

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Just tested this and created 2-3 DMs but not able to reproduce above issue.

Is there any specific use-case in which I have to test to reproduce it?

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
We can close this issue if it is fixed.

**Comment by emilvincentz** [comment]
sounds good
