### ISSUE TITLE
Click on "Chat invite notification" goes into a 404

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1131]
https://github.com/acterglobal/a3/assets/77483554/76ceaf40-f954-42e4-a2ff-29b8aa4b9089

**Comment by gnunicorn** [comment]
Refs https://github.com/acterglobal/a3-meta/issues/54

**Comment by emilvincentz** [comment]
i believe this only happens for push notifications that are "invites"

**Comment by gnunicorn** [comment]
> i believe this only happens for push notifications that are "invites"

Yes, that is very likely. We don't yet really have code to link to an invite directly, showing a room and its content that we don't necessarily know of yet ... and the existing code doesn't handle it right either...

**Comment by emilvincentz** [comment]
understandable, but as of now maybe just redirect all invite requests to activity page?
