### ISSUE TITLE
when typing full username in search, no results is shown

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1134]
A user reported this issue, and I can confirm
The result dissapears when user add the ".global"

https://github.com/acterglobal/a3/assets/77483554/4698ca8f-909b-4555-856e-6a71a64d1761

**Comment by kumarpalsinh25** [comment]
@bitfriend 
Can check below method for above issue?

[acter_flutter_sdk_ffi.dart](https://github.com/acterglobal/a3/blob/main/app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart)
```
/// search the user directory
  Future<FfiListUserProfile> searchUsers(
    String searchTerm,
  ) {
    final tmp1 = searchTerm;
    var tmp0 = 0;
    var tmp2 = 0;
    var tmp3 = 0;
    var tmp4 = 0;
    tmp0 = _box.borrow();
    final tmp1_0 = utf8.encode(tmp1);
    tmp3 = tmp1_0.length;

    final ffi.Pointer<ffi.Uint8> tmp2_0 = _api.__allocate(tmp3 * 1, 1);
    final Uint8List tmp2_1 = tmp2_0.asTypedList(tmp3);
    tmp2_1.setAll(0, tmp1_0);
    tmp2 = tmp2_0.address;
    tmp4 = tmp3;
    final tmp5 = _api._clientSearchUsers(
      tmp0,
      tmp2,
      tmp3,
      tmp4,
    );
    final tmp7 = tmp5;
    final ffi.Pointer<ffi.Void> tmp7_0 = ffi.Pointer.fromAddress(tmp7);
    final tmp7_1 = _Box(_api, tmp7_0, "__Client_search_users_future_drop");
    tmp7_1._finalizer = _api._registerFinalizer(tmp7_1);
    final tmp6 = _nativeFuture(tmp7_1, _api.__clientSearchUsersFuturePoll);
    return tmp6;
  }
```

**Comment by gnunicorn** [comment]
@bitfriend if this turns out to be a rust-side problem, let's make sure to add a new integration test for it alongside the fix.

**Comment by bitfriend** [comment]
@gnunicorn Matrix dev team recognized this issue comes from synapse server.
Will I open issue in synapse project repo?

**Comment by bitfriend** [comment]
When user wants to search `@miles:ds9.acter.global`:
`miles:ds9.acter.global` returns empty.
`miles:ds9.acter` returns empty.
`miles:ds9` returns the correct record.

**Comment by bitfriend** [comment]
Should I make `miles:ds9.acter.global` to `miles:ds9` and do search?
Of course, this is hack.

**Comment by bitfriend** [comment]
> @gnunicorn Matrix dev team recognized this issue comes from synapse server. Will I open issue in synapse project repo?

Kevin let me know [this issue](https://github.com/matrix-org/synapse/issues/7588).
This issue was already reported to synapse project.

**Comment by gnunicorn** [comment]
fixed with https://github.com/acterglobal/a3/pull/2156
