### ISSUE TITLE
Mac desktop app:  Fatal Error - Reference model not found.

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1139]
Every-time when I run app on mac desktop, it is giving below error. 

<img width="792" alt="Screenshot 2023-11-10 at 4 10 44 PM" src="https://github.com/acterglobal/a3/assets/51526480/f19bd595-173d-455d-a345-29f7611f68c2">

**Comment by gnunicorn** [comment]
It appears this is a [general data-not-found error in the core db fetching code](https://github.com/acterglobal/a3/blob/fd3dacaf25f449bc44780da3002948f83d26ada5/native/core/src/store.rs#L29). I'll add some more information to the error message so we have some starting point for debugging.
