### ISSUE TITLE
loading room failed when joining chat in space

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1142]
however if you restart the app, it shows that you have joined.

https://github.com/acterglobal/a3/assets/77483554/04536d7c-c79b-45eb-8a1d-38433d902793

**Comment by gnunicorn** [comment]
https://github.com/acterglobal/a3-meta/issues/94

**Comment by emilvincentz** [comment]
This still persists 
https://github.com/acterglobal/a3/assets/77483554/af60230a-f104-47fb-8db8-36253b6dc1cf

**Comment by emilvincentz** [comment]
this still happens


https://github.com/acterglobal/a3/assets/77483554/94ab2e6b-2073-475d-9041-e53aa901230e
