### ISSUE TITLE
Edit Message : After app restart, it is showing original message instead of edited message 

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1165]
https://github.com/acterglobal/a3/assets/51526480/4ef43487-cc18-43ff-8f59-6b29752f7c26

**Comment by gnunicorn** [comment]
seems to be an issue coming from the underlying rust-API

**Comment by gnunicorn** [comment]
@kumarpalsinh25 we've updated the SDK and I think this is gone. If you still experience it, please reopen this issue.

**Comment by kumarpalsinh25** [comment]
> @kumarpalsinh25 we've updated the SDK and I think this is gone. If you still experience it, please reopen this issue.

Tested with latest main. Issue is still there for encrypted rooms. Sharing screen-recording for the reference.


https://github.com/acterglobal/a3/assets/51526480/a9c32b39-2aff-4152-9152-084446aaaab6

Issue points:
- Edited message doesn't showing on chat listing
- Edited message doesn't persist after app restart. 
- Edit message doesn't pre-populating on input box when we do edit message. #1600
- Edit message view doesn't getting close after click on send button for edit message.

**Comment by gnunicorn** [comment]
@kumarpalsinh25 is this still the case? If so, please reopen.
