### ISSUE TITLE
Onboarding layout issue

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#1177]
Android onboarding page has layout issue.
![image](https://github.com/acterglobal/a3/assets/48786056/abcfd035-7865-4555-b86c-4d049dc712fc)

**Comment by gnunicorn** [comment]
this section generally doesn't float well, or isn't legible -- needs some work and time to make this proper for various screen formats and sizes.

**Comment by bitfriend** [comment]
Windows has the same issue too.
