### ISSUE TITLE
parents space avatar on chat icon doesnt show properly

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1184]
right now only placeholder shows. not the space avatar itself.

![Image](https://github.com/acterglobal/a3/assets/77483554/28049361-7114-4489-aac4-b4b7e394bbfc)

While fixing this one, do we also want to add, multiple space avatars, if a chat is linked to multiple spaces? 
issue: #1122 https://github.com/acterglobal/a3/issues/1122

**Comment by emilvincentz** [comment]
well as far as I know I cant compare as element doesnt show the connected spaces avatar on a room (like we do on Acter)

**Comment by gnunicorn** [comment]
right... sorry...

**Comment by gnunicorn** [comment]
Fixed in #54bd6f602470c89fea13ae94e8b8246284086885 .
