### ISSUE TITLE
Android Emulator: Frequent logout issue.

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1194]
- App gets logout frequently on debug mode
- When we clicks on Acter app icon then also its gets logout and start from onboarding screen

**Comment by gnunicorn** [comment]
can confirm to have the same with the android emulator. but on the released version with my actual phone, it's all good. @kumarpalsinh25 do you also have the issue on the actual hardware?

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
I can confirm that the issue is there on the debug mode.
I have tested on the Android physical device and Emulator on debug mode and faced the given issue.

**Comment by gnunicorn** [comment]
So, despite our sdk storing the sessions:
`I/flutter ( 6697): session stored: [EORIYLRLPX]`

When starting up, it can't find them:
```
I/flutter ( 7070): Secure Storage is available. Attempting to read.
I/flutter ( 7070): Migrated []
I/flutter ( 7070): session stored: []
```


Maybe something on the `FlutterSecureStorage` ... will investigate further.

**Comment by gnunicorn** [comment]
seems to be related to this. trying the mentioned work-a-round: https://github.com/mogol/flutter_secure_storage/issues/566
