### ISSUE TITLE
Implementing Empty states UI 

### ISSUE THREAD

**Issue by kokodavid** [acterglobal/a3#1198]
- [x] DMs Empty State
- [x] Pins Empty State
- [x] Events Empty State
- [x] Chat Empty State
- [ ] Spaces Empty State
- [x] Activity Empty State
- [x] Home Empty State
- [x] Updates Empty State
- [ ] Connection Lost Error State

**Comment by kokodavid** [comment]
Chat Empty state
![chat empty state](https://github.com/acterglobal/a3/assets/47295684/57981cac-3837-45fa-9a6a-947b1c0175e6)

**Comment by kokodavid** [comment]
Activities empty state
![activity state](https://github.com/acterglobal/a3/assets/47295684/caa225b4-390d-4043-a82e-8039d33b2d18)

**Comment by kokodavid** [comment]
Pins empty state
![pin empty state](https://github.com/acterglobal/a3/assets/47295684/9f1ec24d-1fe5-4444-90bd-7af7e5bb99ef)

**Comment by kokodavid** [comment]
Events empty state
![events state](https://github.com/acterglobal/a3/assets/47295684/c9743752-2c19-40de-b5a7-31fbd0240a1f)

**Comment by MirekKolaja** [comment]
@kokodavid - Minor issue - there is a typo in the empty state for Space - Chat

collaboratring > collaborating

**Comment by kokodavid** [comment]
Updates empty state
![image](https://github.com/acterglobal/a3/assets/47295684/c491819c-3518-4f45-aafa-f219cdea333b)

**Comment by kokodavid** [comment]
DMs empty state
![image](https://github.com/acterglobal/a3/assets/47295684/aa9f62ae-0ecc-458b-b39e-782d37efb3a4)

**Comment by kokodavid** [comment]
Home Empty state
![image](https://github.com/acterglobal/a3/assets/47295684/eae8f58b-8549-42ee-ba66-5eecc59af27f)

**Comment by kokodavid** [comment]
I have had a challenging time in determining where to add the empty state for the connected spaces. @gtalha07 maybe you can help with that. I have included the widget in the page **related_spaces_page.dart**. Also does the connectivity package work ?

**Comment by kokodavid** [comment]
To work on empty state: Activity page:
@kokodavid
