### ISSUE TITLE
adding media kit broke linux build

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1205]
Latest nightly doesn't contain any linux build [because of the new media_kit package](https://github.com/acterglobal/a3/actions/runs/7155279328/job/19483726685#step:21:80). Is it missing something on the build-servers? Or is there something else going on?

**Comment by kumarpalsinh25** [comment]
Reference Data:
https://github.com/media-kit/media-kit#gnulinux-1

**Comment by gnunicorn** [comment]
looks like we need to update the linux build and packaging process to fix this.
