### ISSUE TITLE
Push notifications on iOS show fatal error)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1217]
![image](https://github.com/acterglobal/a3/assets/77483554/4074d2e7-a7fa-4ae2-b2ec-908e55c57272)

**Comment by emilvincentz** [comment]
Worked at some point when I nuked all data, but then errror came back

**Comment by gnunicorn** [comment]
This references an old session that isn't live anymore but we still receive notifications for...

**Comment by emilvincentz** [comment]
Still recieve this fatal error, but only on push notifications for chat invites

**Comment by emilvincentz** [comment]
When clicking on a push notifcations that leads to a space invite, beside the fatal error, it also shows a loading icon, that only dissapears when i click on "accept"



https://github.com/acterglobal/a3/assets/77483554/f5656540-fe65-464a-a477-9554ccdd63d3
![Image](https://github.com/acterglobal/a3/assets/77483554/642d396e-ffed-4c02-bd33-e97e2c85fe1b)

**Comment by emilvincentz** [comment]
When clicking on a push notifcations that leads to a space invite, it shows a slighly diferent error page:


![Image](https://github.com/acterglobal/a3/assets/77483554/ca0d46dd-6e26-47b2-8c87-bfd1d0a09019)

**Comment by gnunicorn** [comment]
should be fixed by #1353 . Please reopen if this still persists after the next nightly.
