### ISSUE TITLE
Verifying sessions on MacOS & iOS doesnt work (signature upload failed)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1222]

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/599711e1-5cc9-418d-a5af-42b32a683f36)
![Image](https://github.com/acterglobal/a3/assets/77483554/068d314f-9d74-4ee2-bea8-21676bd96fcd)

**Comment by emilvincentz** [comment]
Getting the same error on IOS (Iphone SE)
With latest build 1.23.1228/IOS

**Comment by emilvincentz** [comment]
in addition, Tryied to log out of IOS and in again. 
Element Desktop app recognizes the new device (iphone) but Acter desktop does not. 
see images below

![Image](https://github.com/acterglobal/a3/assets/77483554/11130f03-1116-4c90-84b4-a839b5d0cb5c)
![Image](https://github.com/acterglobal/a3/assets/77483554/5651d284-459a-4f74-abfc-946beed092ec)

**Comment by emilvincentz** [comment]
any updates on this one @bitfriend ? 
Would love to showcase Acter to a new client/customer next week, but currently not able to show messages on mobile as i cant verify sessions.

**Comment by emilvincentz** [comment]
yes, its just that there's certain messages that I won't to show with some of the we risers, who I now cant decrypt. But will work around it

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/e58689c2-a9bc-4a2a-ad8f-7f18b70f6456)



![Image](https://github.com/acterglobal/a3/assets/77483554/78b5e2d0-961f-4473-9d1d-23967eed5dc0)
![Image](https://github.com/acterglobal/a3/assets/77483554/6d8bf65a-2f99-4b4c-b360-8a9f9c9092c5)
![Image](https://github.com/acterglobal/a3/assets/77483554/e28ad0fc-3569-4b83-b798-110b8fcb3b7f)
![Image](https://github.com/acterglobal/a3/assets/77483554/a15aabea-c7f2-44d0-b42b-65eeefad4a81)

**Comment by emilvincentz** [comment]
@gnunicorn  okey, verificaiton now works again. 
both on Ios and web version. 

What helped was i logged out and in again on ios. 
On Macos, when i opened Acter, it said "fatal erro os error 1" or something like that. 
Then i nuked all data and logged in again. This time verification went through. 

However, Ui on buttons are still messed up on Ios (Ipone SE Gen3)

**Comment by gnunicorn** [comment]
seems like the latest matrix-rust-sdk update fixed this. the UI bugs are reported in a separate issue.
