### ISSUE TITLE
When editing message, it shows html or whatever the name is

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1230]
![Uploading 290892597...]

**Comment by gnunicorn** [comment]
@emilvincentz misses the actual screenshot. Maybe you want to edit this?

**Comment by emilvincentz** [comment]
Yeah sorry was on the train so bad connectivity 

![image](https://github.com/acterglobal/a3/assets/77483554/0f4128d3-34ea-4b2b-af8a-7f729adcb30f)
