### ISSUE TITLE
stuck on loading when downgrading user from "admin" to "regular"

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1235]
Tested on IOS (latest version9

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Is this issue still exists?

**Comment by gnunicorn** [comment]
> that an admin can not downgrade another admin?

Yes, that is matrix spec. We could make a check to prevent this from even being an option and tell the user why though. Let's make that a separate issue.
