### ISSUE TITLE
Logout/Remove session not working

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1239]
Tested with...
- iPhone 12
- iOS 17.1
- 

https://github.com/acterglobal/a3/assets/51526480/fd1b3778-2ee6-4006-986f-bea60dd250f7

**Comment by gtalha07** [comment]
Same [thoughts](https://github.com/acterglobal/a3/issues/1240#issuecomment-1864417496), the functionality isn't there. We need to remove these buttons.

**Comment by kumarpalsinh25** [comment]
> Same https://github.com/acterglobal/a3/issues/1240#issuecomment-1864417496, the functionality isn't there. We need to remove these buttons.

#gnunicorn 
You mentioned that this is not expected behavior. Any thoughts on this?

**Comment by kumarpalsinh25** [comment]
> Same https://github.com/acterglobal/a3/issues/1240#issuecomment-1864417496, the functionality isn't there. We need to remove these buttons.

@gnunicorn 
You mentioned that this is not expected behavior. Any thoughts on this?

**Comment by gnunicorn** [comment]
pretty sure this was functional once. this seems like a regression we need should fix and add a ui-test-case for.
