### ISSUE TITLE
Dont recieve notifications on iOS anymore

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1261]

**Comment by emilvincentz** [comment]
Dont know with which update it happened, but now i dont recieve any push notifcaitons on Acter.
However they still coming from element. 
Testing on Ipone SE (v.1.23.1228/iOS)

**Comment by gnunicorn** [comment]
@emilvincentz just to be sure, can you check the system settings and confirm acter is still allowed to show/sent/receive push notifications?

**Comment by emilvincentz** [comment]
@gnunicorn yep, checked both app settings and phone settings and also tried to restart app an my phone, but all seems good

**Comment by gnunicorn** [comment]
Just confirmed that it generally works. Then checked your setup and it appears that our server isn't set up to be a push target for your account @emilvincentz: 
![image](https://github.com/acterglobal/a3/assets/40496/22990bba-d596-4ffd-aded-aa793110d0b9)

Could you navigate to acter -> settings -> navigations, toggle the push button there and try again?

![Screenshot_1704802941](https://github.com/acterglobal/a3/assets/40496/f817f896-f2c5-4b4a-8c97-50971befd04b)

**Comment by gnunicorn** [comment]
works again.
