### ISSUE TITLE
Some pins and updates are not showing on IOS and MacOS

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1264]

**Comment by emilvincentz** [comment]
When viewing on mobile they show, but not on desktop.
testing on v.1.23.1421/MAcos

![Image](https://github.com/acterglobal/a3/assets/77483554/ac8ad502-ff0d-448b-bd70-c27cb3713d13)

**Comment by emilvincentz** [comment]
Now after the latest nightly, also no pins or events are shown.

**Comment by emilvincentz** [comment]
or actually its not all, but most.
The updates from two spaces (Beacon and a test space) is still showing. And the events and pins are interestingly also showing in those two spaces.
However none of the others i created, including from the Acter.global is showing updates, events or pins.

**Comment by gnunicorn** [comment]
whenever that happens again, please submit the logs and we can have a look.
