### ISSUE TITLE
appflowy as inline wysiwyg editor

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1274]
Add a labs flag to allow replacing the current `markdown`-editor with an inline editor based on [appflowy_editor](https://pub.dev/packages/appflowy_editor) for editing Pin content.

**Comment by gnunicorn** [comment]
Starting point [happened here](https://github.com/acterglobal/a3/commit/ada320f21176afafaf03d082054e7c1789bc13e7)

**Comment by gtalha07** [comment]
Closing as completed. Refs PR -> #1366.
