### ISSUE TITLE
Too many `/devices` requests upon login

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1276]
With emilio, with a total of `162` session logging in for the first time on a device, issues a whopping `65` distinct requests to `/devices` all with the same result ...

there is something wrong here...

<img width="786" alt="Screenshot 2024-01-15 at 17 15 05" src="https://github.com/acterglobal/a3/assets/40496/ee54b10e-bb25-4564-82ee-2e1bda824db5">

**Comment by bitfriend** [comment]
Also I got this error on emil test account.
`[2024-01-16][23:02:34][matrix_sdk_crypto::identities::manager][WARN] Failed to update device keys user_id="@emil:acter.global" device_id="PWRVRMBNTR" error=VerificationError(Signature(signature::Error { source: Some(Verification equation was not satisfied) }))`
BTW I don't know why this error occurred for now.
