### ISSUE TITLE
too many requests upon starting up

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1278]
other than the `/device`-requests (see #1276 ) just starting up and clicking around into chat and here and there a bit, there are too many requests taking place upon starting up with an existing session:

<img width="800" alt="Screenshot 2024-01-15 at 17 30 36" src="https://github.com/acterglobal/a3/assets/40496/9956b8b8-66d5-4ee6-b51a-66a13acae8a9">

We see:
 - a request to `$roomId/messages?dir=b&limit=20` for every space
 - a request to `$roomId/messages?dir=f&limit=100` for every space
 - several calls to `$roomId/members`
 - several calls to `thumbnail/$server/$ID` that should already have been cached previously - effectively no image changed since the last startup, why are we fetching remote content at all?
 - a request to `$roomId/messages?from=t1-XXXX` for every space

with a total of over 200 requests in just the first 16 seconds of startup...  too many!

**Comment by bitfriend** [comment]
Now app launching seems to become fast somewhat.
