### ISSUE TITLE
Weird spacing for space with many users on desktop

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1279]
Went into the acter.global space with more than 100 users and found the following UI glitches on mobile:
<img width="800" alt="Screenshot 2024-01-15 at 17 27 06" src="https://github.com/acterglobal/a3/assets/40496/449297c7-4748-44dd-b336-531521f68b44">

- [x] Spacing per member is way to large ..
- [x] the number in the +-counter on the top wraps rather than resizes

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
There is also weird space issues on Sub-spaces list view.
![Screenshot 2024-01-17 at 12 56 30 PM](https://github.com/acterglobal/a3/assets/51526480/578adc24-795a-4501-beb7-3cefac433a5a)

**Comment by kokodavid** [comment]
We can have it this way @gnunicorn @kumarpalsinh25 
![image](https://github.com/acterglobal/a3/assets/47295684/85fd269a-5ce4-4df2-8eac-0b7538eac749)

**Comment by gnunicorn** [comment]
this isn't high priority, I just noticed it when running and didn't want to forget about it. that said, if you feel passionate about it and can do it in a rather quick time, go for it regardless :)
