### ISSUE TITLE
Miscellaneous functional issues on Task Module

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1285]
- Task list creation not working
- Task add not working
- Task list sometime showing empty or only loading few task list. It does not showing entire task list of selected space
- Task due date assignment not working sometimes
- Task user assignment not working sometimes

Test with..
- iOS Nightly 2024-01-17
- iPhone 12
- iOS 17.2.1

Reference Videos:
- https://github.com/acterglobal/a3/assets/51526480/a32d9447-c6af-4340-9d0f-b15c72eaa548
- https://github.com/acterglobal/a3/assets/51526480/b89764c3-2851-451d-b4d4-6cf0a05f5633

**Comment by gnunicorn** [comment]
does the tasks e2e test suite work for you?

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
This is how e2e test suite result shows in my system for Task Module.
![Screenshot 2024-01-19 at 3 22 51 PM](https://github.com/acterglobal/a3/assets/51526480/9b595d7e-97ac-4946-bfe7-2565b37fe036)

1) Error in `New TaskList and tasks via quickjump`
![Screenshot 2024-01-19 at 3 26 12 PM](https://github.com/acterglobal/a3/assets/51526480/d95715e6-d9a3-4ee2-b77e-6b5368398cd6)

2) Error in `Change due date`
![Screenshot 2024-01-19 at 3 27 13 PM](https://github.com/acterglobal/a3/assets/51526480/fbec286a-8242-4279-8ad7-1bdb4b00ccd0)
![Screenshot 2024-01-19 at 3 27 32 PM](https://github.com/acterglobal/a3/assets/51526480/e6652722-3b43-4d0a-b660-595d87e46141)
![Screenshot 2024-01-19 at 3 28 03 PM](https://github.com/acterglobal/a3/assets/51526480/e868fbb6-0992-4fec-9fd4-8cb563e91bb9)
![Screenshot 2024-01-19 at 3 28 18 PM](https://github.com/acterglobal/a3/assets/51526480/6e58d2ec-9821-4ddc-808e-8b5b665dd64e)

3) Error in `Change body`
![Screenshot 2024-01-19 at 3 29 06 PM](https://github.com/acterglobal/a3/assets/51526480/a370d290-58fc-41d5-a5e0-5b173eb4d739)
![Screenshot 2024-01-19 at 3 29 20 PM](https://github.com/acterglobal/a3/assets/51526480/130d187d-7171-4199-a135-9513a0e685bb)
![Screenshot 2024-01-19 at 3 29 42 PM](https://github.com/acterglobal/a3/assets/51526480/69703c8a-6367-4d48-b980-50f69cb38760)

4) Error in `Full multi use run`
![Screenshot 2024-01-19 at 3 30 31 PM](https://github.com/acterglobal/a3/assets/51526480/e4da338b-d208-49e3-bda3-2bc7d9bc481a)
![Screenshot 2024-01-19 at 3 30 50 PM](https://github.com/acterglobal/a3/assets/51526480/17345469-ed90-4bc8-934c-2aebbfd68143)

**Comment by gnunicorn** [comment]
so, it some times works and some times does not... interesting ...

**Comment by kumarpalsinh25** [comment]
Yes true, same issue I’m facing in iOS app as well. Sometimes everything works fine and sometimes it doesn’t.

**Comment by gnunicorn** [comment]
fixed in #1308
