### ISSUE TITLE
Miscellaneous UI-UX issues on Task Module

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1286]
- - - - -
**Home Screen**
- - - - -
![WhatsApp Image 2024-01-17 at 13 04 14](https://github.com/acterglobal/a3/assets/51526480/1eec7cec-cb15-40be-95ac-ffe6d2ef33b9)

- - - - -
**Task Details Screen**
- - - - -

![WhatsApp Image 2024-01-17 at 13 04 16 (1)](https://github.com/acterglobal/a3/assets/51526480/853d9026-278e-4504-a5e8-c8867d43602c)

- - - - -
**Task List Screen**
- - - - -

![WhatsApp Image 2024-01-17 at 13 04 16](https://github.com/acterglobal/a3/assets/51526480/582aada4-8750-4600-9b38-ccb874a48124)
![WhatsApp Image 2024-01-17 at 13 04 19](https://github.com/acterglobal/a3/assets/51526480/9a372313-f294-477b-96e0-3cb1b07fbc85)

- - - - -
**Create Task Screen**
- - - - -

![WhatsApp Image 2024-01-17 at 13 04 19 (1)](https://github.com/acterglobal/a3/assets/51526480/1b4af9b4-25e1-4c7a-8c55-5fdb161ec488)

**Comment by kokodavid** [comment]
My Android App on a physical device keeps crushing and I can't get screenshots.
![image](https://github.com/acterglobal/a3/assets/47295684/bea9a39b-f181-4f45-89e4-83e751f856fb)
![image](https://github.com/acterglobal/a3/assets/47295684/50702a11-f6b6-4dc1-ba52-733b799272c3)
![task details](https://github.com/acterglobal/a3/assets/47295684/91bbf426-6e23-497b-962d-20954ef991de)
![image](https://github.com/acterglobal/a3/assets/47295684/8fa4b951-a7db-4f9a-a1b5-d5b3a51ecfea)

**Comment by kumarpalsinh25** [comment]
@kokodavid 
1) Please raise the issue about the app crash with logs or scenario.

2) Can we improve below design?
![Screenshot 2024-02-13 at 12 26 03 PM](https://github.com/acterglobal/a3/assets/51526480/ffaf401d-d7d1-488d-9e01-0ba293709ba3)

**Comment by kokodavid** [comment]
1. Alright, I'll do that. 

2. Should I redesign the whole feature, or just the section page?
@kumarpalsinh25

**Comment by kumarpalsinh25** [comment]
> Yes we can, should I redesign the whole feature, or just the section page?

Task section area.

**Comment by gnunicorn** [comment]
thanks, @kokodavid

**Comment by kokodavid** [comment]
![image](https://github.com/acterglobal/a3/assets/47295684/f13de2d8-382a-4c55-9103-0f12a2d8b583)

![image](https://github.com/acterglobal/a3/assets/47295684/a889df1d-82fc-45c5-bf99-acd2ce2f9b2a)

**Comment by gnunicorn** [comment]
fixed in #1377
