### ISSUE TITLE
Session reset on every open

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1304]
it appears that we are resetting the session every time the app is opened/the login procedure starts. Indicated by the logs in https://github.com/acterglobal/a3-meta/issues/77 and  https://github.com/acterglobal/a3-meta/issues/76 . I suspect this is happening since the changes in https://github.com/acterglobal/a3/commit/53faff09fda7ff1afd7a09c7b4304aeb946ad5fd - most notably, the removed `false` from [Line 180](https://github.com/acterglobal/a3/commit/53faff09fda7ff1afd7a09c7b4304aeb946ad5fd#diff-72881b6a7bf91b53b02737e213db350af8b290924f67c48bff42376ea0729781L180).

This is bad for a few reasons: we are super slow in starting up, as we sync up everything; as the db is moved, nothing is shown from the cache; we are adding a new device every time;

**Comment by bitfriend** [comment]
Yeah, for example Talha and I are using Emil test account for space testing.
We often switch between self account and emil test account and it occurs several times of logout and login.
Actually we are seeing bulk of `new device alert` on every login to emil test account.

**Comment by gnunicorn** [comment]
> Actually we are seeing bulk of new device alert on every login to emil test account.

While the bug increases the number of sessions this is not the cause of seeing to many of these device alerts. They come regardless of us creating even more session just because we use that account a lot for testing. That needs a secondary fix for the UI for new device alerts regardless.
