### ISSUE TITLE
notification doesn't sent me to the right chat/update upon open/click

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1362]
Android, latest release, upon receiving a notification in an encrypted chat, it doesn't open the app to go there:

https://github.com/acterglobal/a3/assets/40496/087ef021-af76-4a9c-968d-14a1520f6f19

**Comment by gnunicorn** [comment]
as reported in #1502 the same is true for opening updates.

**Comment by emilvincentz** [comment]
I have bumped this up in priority, as i see some of the users im testing with who find this quite confusing. also as we dont have any in app notifcation indicators.

**Comment by gnunicorn** [comment]
> also as we dont have any in app notifcation indicators.

what does that mean? and shouldn't this be a different issue?

**Comment by emilvincentz** [comment]
I ment that we dont have indicators for unread chats for example. And yes, this is a different issue
