### ISSUE TITLE
Visibility and accessibility

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1379]
- [ ] It needs to be very clear, what the visiibilty and accessability is for the space or chat you are in. Like, can anyone join? can everyone see it but needs to be approved or is it hidden and invite only? 
- [ ] We need figure out how users manage the visiblity and acccesability settings when they create a space or chat (maybe also event) and also how they modify it later on.

For spaces and chat we are bound by the matrix protocol, so would be good to look at element or other matrix clients to figture out how they do it.

**Comment by kokodavid** [comment]
https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=10393-234399&mode=design&t=jTgCGAhohpLBggJe-4

Update document

**Comment by kokodavid** [comment]
![Image](https://github.com/acterglobal/a3/assets/47295684/a7ad2a68-9378-4703-abd5-2facd1b2eaca)

**Comment by emilvincentz** [comment]
Example of user cases:
- When going to chats under a space, its needs to show, if the chat is shared with other spaces (through the small avatars)
- Needs to be clear for the user, that if they invite people to a subspace, what access they will have. Will they also be able to see that parent space? the same for chats.
- It needs to be clear what status a space/chat has (is it open, restricted, private etc)?¨
- If a space has mulitple parents, do the parent spaces also figure as small avatars?
Please feel free to reach out @kokodavid if you would like to jump on a call and discuss some of these things together.

**Comment by gtalha07** [comment]
- Listing Rooms Visibility .i.e whether room is searchable on public room list directory. The [spec](https://spec.matrix.org/v1.10/client-server-api/#listing-rooms) dictates that can either be `Public` or `Private`.
- Room Accessibility aka `join_rules`.i.e. https://spec.matrix.org/v1.10/client-server-api/#mroomjoin_rules. 
This is shared in reference of designing UI.

**Comment by gnunicorn** [comment]
this is done.

**Comment by emilvincentz** [comment]
@gtalha07 just checking if this will be implemented for chat as well?
