### ISSUE TITLE
Message Editing

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#138]
We want allow users to edit chat messages after they've been sent. The matrix network already allows for that (sending the edited message as a new event relating to the old one), but we still need:

- Design what that should look like in the UI?
- the core SDK:
  - keeping track of the current state per message
  - alerting the UI if the state has changed post having been sent
- the UI for editing and for updating the existing message (when other users sent them in)

**Comment by gtalha07** [comment]
API References: https://pub.dev/documentation/flutter_chat_ui/latest/flutter_chat_ui/Chat/isTextMessageTextSelectable.html
https://pub.dev/documentation/flutter_chat_ui/latest/flutter_chat_ui/Chat/textMessageBuilder.html
https://pub.dev/documentation/flutter_chat_ui/latest/flutter_chat_ui/Chat/customMessageBuilder.html
