### ISSUE TITLE
can't select text of text-slide

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1389]
(on desktop) I am looking at a text slide and would like to select the content so I can copy-paste it somewhere else, but I can't :( . Either the selection doesn't show or it simply refuses to select anything.

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Are you referring to the view mode or Edit mode?

1) On view mode, generally text selection or directly copy feature not there. And it externally provided in more button if needed.

2) On edit mode, select text and cut-copy-paste everything working. Sharing video for reference.
https://github.com/acterglobal/a3/assets/51526480/e3cadc9e-296e-4c92-b4f5-a7dac421003b

**Comment by gnunicorn** [comment]
I am referring to looking at the update on desktop and wanting to select some text so I can copy-paste it somewhere else ... that didn't work, but potentially should.

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
In mobile app development, by default text View never be like we can select and copy the content similar to websites. We can do relevant coding to provide this feature if needed but I generally not see this type of things on other platforms as well.

**Comment by gnunicorn** [comment]
@kumarpalsinh25 I did mention I was talking about desktop though...
