### ISSUE TITLE
News Update : Video doesn't fit to the screen size

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1407]
The video preview is very small. But when in the creation form but also when displayed.

![Image](https://github.com/acterglobal/a3/assets/77483554/36b3d50a-6ead-423f-9aff-4d8bd0c964ee)
![Image](https://github.com/acterglobal/a3/assets/77483554/5752c27c-f7c0-4d43-9238-d0fd742f5833)

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Can you share the video file that you are using in this news post?

**Comment by emilvincentz** [comment]
yep.

**Comment by emilvincentz** [comment]
https://github.com/acterglobal/a3/assets/77483554/5614174c-df20-4230-a7a8-ce7039bfab81

@kumarpalsinh25
