### ISSUE TITLE
News Update: Unable to add link to the text. Always gets hidden behind the keyboard

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1410]
https://github.com/acterglobal/a3/assets/51526480/1123c1c6-baba-440f-bc8d-5ae08b94ca32

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
I have check that [AppFlowy Editor Example](https://github.com/AppFlowy-IO/appflowy-editor/tree/main/example) code also have this issue in mobile view.
Any thoughts on alternative solution?

**Comment by gnunicorn** [comment]
> I have check that [AppFlowy Editor Example](https://github.com/AppFlowy-IO/appflowy-editor/tree/main/example) code also have this issue in mobile view.
Any thoughts on alternative solution?

report it to the applfowy editor bug tracker?!?

**Comment by kumarpalsinh25** [comment]
> report it to the applfowy editor bug tracker?!?

Yes checked the issues list and found the similar issue ticket but it was closed and still issue is persist.
https://github.com/AppFlowy-IO/appflowy-editor/issues/278

I have added comment over there, I don't know how to re-open it.
https://github.com/AppFlowy-IO/appflowy-editor/issues/278#issuecomment-1962242545

**Comment by gnunicorn** [comment]
was an appflowy problem.
