### ISSUE TITLE
Update display bugs

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1413]
Viewed on iphone 12

![Image](https://github.com/acterglobal/a3/assets/77483554/bd87ec7a-84b5-4c05-a9bf-4b232cdf9bdd)
![Image](https://github.com/acterglobal/a3/assets/77483554/312cf8d8-3364-44cb-83a9-14a068dd0fcf)
![Image](https://github.com/acterglobal/a3/assets/77483554/5ecbc058-ff0d-4508-93fd-051b787425dd)

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
Are you testing on latest nightly build?
