### ISSUE TITLE
Expand Video & Image preview size, allow to pinch-to-zoom

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1416]
On IOS 

https://github.com/acterglobal/a3/assets/77483554/20613aac-3a3d-4c2d-bfb2-6909e52fd124

Also images shows long title.

https://github.com/acterglobal/a3/assets/77483554/29f5665f-dc9c-418b-adee-fd9deddb0baa

**Comment by gnunicorn** [comment]
would be nice to be able to zoom in as well.
