### ISSUE TITLE
Ui bugs in Chat Room Details

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1421]
Somehting about the about section of chats that doesnt look smooth,
Also on iphone SE, when scrolling down, you losee the "back" arrow

![Image](https://github.com/acterglobal/a3/assets/77483554/7bd66b2e-8d2e-4468-857e-b7bef3ddf446)

**Comment by kumarpalsinh25** [comment]
Weird bugs, It looks fine on the android app. Let me check that and do the needful.

Android App:
![Image](https://github.com/acterglobal/a3/assets/51526480/48f52f43-2321-40a1-904a-42af45366143)
