### ISSUE TITLE
"deserializationFailed"

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1427]
this showed up after the latest ios verison: 1.24.222
It kept showing after reopining the app a couple of times. 
Now its finally gone (for now).

![Image](https://github.com/acterglobal/a3/assets/77483554/ec08eab6-049a-421d-bc8f-fb1122aa6a02)

**Comment by bitfriend** [comment]
`DeserializationFailed` is based on `ErrorBody::NotJson` from `matrix-sdk`.
This error comes from `matrix-sdk`.

**Comment by gnunicorn** [comment]
can you submit the previous-run logs from within the bug reporter? I have also recently seen this and submitted them.

**Comment by emilvincentz** [comment]
@gnunicorn cna not access the bug reporter when this error shows. Also not with rage shake
