### ISSUE TITLE
add "preview" label

### ISSUE THREAD

**Issue by JMEFKT** [acterglobal/a3#1439]
- [ ] within app stores (logo & description)
- [ ] at app icon showed on devices
- [ ] on all welcoming/first screens

**Comment by JMEFKT** [comment]
![share_3357088051187704037](https://github.com/acterglobal/a3/assets/116185441/0d80d8ac-277b-46a4-8452-6ea3f4ee4bda)

**Comment by gnunicorn** [comment]
I've slept over this and I don't quite agree on this change (anymore). I see it could do some harm for us in marketing/communication especially with investors and I just don't see: Why do we want this? What problem does it solve?

**Comment by JMEFKT** [comment]
wrong expectations from users, like the entire last months or year, users that never come_came back or wait for "day X"

maybe just mention it @welcoming & app store?
