### ISSUE TITLE
option to show password @registration

### ISSUE THREAD

**Issue by JMEFKT** [acterglobal/a3#1440]
to double-check what one was typing in

[belongs to #1444]

**Comment by MirekKolaja** [comment]
For the reference, you can take a look at this design how the password visibility should looks like over [here](https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=10209-21931&mode=design&t=zQexl6nXBrNXQwe0-4):

https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=10209-21931&mode=design&t=zQexl6nXBrNXQwe0-4

The eye icon can be found in the Atlas Icon library under "eye".
