### ISSUE TITLE
implement app walkthrough 

### ISSUE THREAD

**Issue by JMEFKT** [acterglobal/a3#1442]
showing after first sign-in (skip optionally) & available in settings for recap.
https://www.notion.so/acter/Tops-issues-for-app-walkthrough-c585ffd6968e4b2d81f3118e20eab48f

General Navigations:

1) Home Tab: Here you find your spaces and an overview of all upcoming events & pending tasks of these spaces.
2) Update Tab: News stream on the latest updates & calls to action from your spaces. 
3) Chat Tab: It's the place to chat – with groups or individuals. chats can be linked to different spaces for broader collaboration.
4) Activity Tab: Important information from your spaces, like invitations or requests. Additionally you will get notified by Acter about [how can we call that..."security issues" sounds frightening]
5) Quick Jump Tab: Like a search engine to quick jump to [what actually - is it just spaces & pins for now?]

Space Overview:

1) Space Details: A space is the starting point for your organizing. Create & navigate through pins (resources), tasks and events. Add chats or subspaces.
2) Join Space or Create Space: Join an existing space on our Acter server or in the Matrix universe or set up your own space. [would just show the options & end there for now]

**Comment by JMEFKT** [comment]
https://github.com/acterglobal/a3/assets/116185441/32c3ca5c-0936-48cf-96ff-27ec7e490773

**Comment by JMEFKT** [comment]
what do you think about my copy @kumarpalsinh25...there are also some parts still missing or aren't totally concrete yet

**Comment by kumarpalsinh25** [comment]
> what do you think about my copy @kumarpalsinh25...there are also some parts still missing or aren't totally concrete yet

Thanks @JMEFKT for updating description. I will check and put it. 

Also update description wherever needed :)
