### ISSUE TITLE
New Entry Screen

### ISSUE THREAD

**Issue by JMEFKT** [acterglobal/a3#1443]
with community stuff included

design interations: design iteratons: https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=11055-15615&mode=design&t=Sa698FCXCaPcxgGF-4

**Comment by MirekKolaja** [comment]
@kumarpalsinh25 - The entry screen was iterated and now is ready for Dev - Link in the description leads to the final version
