### ISSUE TITLE
Update Registration Screen

### ISSUE THREAD

**Issue by JMEFKT** [acterglobal/a3#1444]
provide (linked) information on how Acter is safe+secure, why to always remember username, email address only optional, add #1441 & #1440 etc.

design iteratons: https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=10416-11883&mode=design&t=zQexl6nXBrNXQwe0-4

examples for next level registration: https://miro.com/app/board/uXjVMlxEtAU=/?moveToWidget=3458764580888038792&cot=14

**Comment by JMEFKT** [comment]
other examples: https://miro.com/app/board/uXjVMlxEtAU=/?moveToWidget=3458764580888038792&cot=14

**Comment by MirekKolaja** [comment]
@kumarpalsinh25., the sign up form is now ready for Dev including these changes:

- [ ] Adding eye icon to see/unsee the password
- [ ] Spacing between input fields so there is a space for error Indicators
- [ ] Labels and the input fields are separately + there is a Plaholder text in the input fields
- [ ] renaming "Code" to "Invite Code"
- [ ] Invite Code tooltip with explanation with what it is
- [ ] Adding screens for "Save Username" and "Linking Email to Profile"

The final designs can be found here: 

https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=11055-15617&mode=design&t=Sa698FCXCaPcxgGF-4

**Comment by emilvincentz** [comment]
Hey @kumarpalsinh25 
Just saw that there is a few bugs on the registrations screens.
1. On iphone SE you can not see the login button, only signup and also you can scroll
2. There is a lot of black space at the top


![Image](https://github.com/acterglobal/a3/assets/77483554/950a5340-de38-4d7c-8728-ecf9e70cef2e)
![Image](https://github.com/acterglobal/a3/assets/77483554/9320042a-f056-4a5f-821e-a8744c02bd90)

**Comment by kumarpalsinh25** [comment]
Opps! I will do the needful for smaller screens support.

**Comment by JMEFKT** [comment]
the copy of the invite code explanation/tool tip needs to be adjusted & might also include an invite code itself (update beginning of next week)

**Comment by JMEFKT** [comment]
not sure about the "e.g. for password recovery" part, that's a new addition, don't think we have that flow, that sounds like an automated process

![Image](https://github.com/acterglobal/a3/assets/116185441/8d14e11b-0a0a-4c6c-9613-3e05e2f10e10)

**Comment by JMEFKT** [comment]
and "email address" is written wrong 😅

**Comment by kumarpalsinh25** [comment]
> the copy of the invite code explanation/tool tip needs to be adjusted & might also include an invite code itself (update beginning of next week) @MirekKolaja @kumarpalsinh25

I have implemented flow based on the figma design last week but ya I can update the details about invite code info dialog as suggested.

**Comment by kumarpalsinh25** [comment]
@JMEFKT 
We have separate tickets for above issues. You can update date over there. :)

1) Add optional email address:
https://github.com/acterglobal/a3/issues/920

2) Forgot Password:
https://github.com/acterglobal/a3/issues/1545

3) Registration : Update invite code description
https://github.com/acterglobal/a3/issues/1546
