### ISSUE TITLE
Update Login Screen

### ISSUE THREAD

**Issue by JMEFKT** [acterglobal/a3#1445]
additional information (pop-up or link) regarding "forgot password" > #1446 needed

design iteratons: https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=10416-11883&mode=design&t=zQexl6nXBrNXQwe0-4

**Comment by MirekKolaja** [comment]
The new login screens are here:

Changes made:

- [ ] Adding icon to see/unsee the password when typing
- [ ] Copy changes

https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=11055-15619&mode=design&t=Sa698FCXCaPcxgGF-4

**Comment by JMEFKT** [comment]
is there already an email address linked @kumarpalsinh25? it's supposed to be support@acter.global (which does exist now). we might also need to really write that email address down on this screen in case people don't have an email app on their device or else @MirekKolaja.

<img width="341" alt="Bildschirmfoto 2024-03-23 um 10 04 35" src="https://github.com/acterglobal/a3/assets/116185441/ad17d716-2919-458c-9717-55cc1f5924eb">

**Comment by kumarpalsinh25** [comment]
@JMEFKT 
Currently on click of `Contact Acter Support`, I'm redirecting user to https://next.acter.global/contact-us, but if we want to open  default mail app with `support@acter.global` then I can do the needful change here in this flow. Open for suggestion! :)

**Comment by JMEFKT** [comment]
jep, open default mail app PLUS mentioning/highlighting this email address support@ on this screen is the better & a more direct option, cause the right people get the request & there is no extra tool like our website builder involved, already email is pretty "unsave" for this transaction

**Comment by kumarpalsinh25** [comment]
> jep, open default mail app PLUS mentioning/highlighting this email address support@ on this screen is the better & a more direct option, cause the right people get the request & there is no extra tool like our website builder involved, already email is pretty "unsave" for this transaction

Ok got it. Created separate ticket https://github.com/acterglobal/a3/issues/1545. It will be done.
