### ISSUE TITLE
New Event: Change the way setting a date works

### ISSUE THREAD

**Issue by natrius** [acterglobal/a3#1467]
So, i tried to create a new event, set the name, selected a date and a time and pressed "OK" and ran into an error about `Invalid Date Time Range. Please select valid dates.`. To make the behavior better or more intuitive i suggest the following:

On start-date change the "OK" to "Next" and switch it back to "OK" when on the "End Date". 
Additionally, automatically switch the "End Date" to the same as "Start Date" + defineable length (best defineable in settings as in a regular calendar application).

**Comment by gnunicorn** [comment]
this has recently been fixed in #1437 , just merged this morning. Will be available in the next nightly and next release.
