### ISSUE TITLE
Updates -> Space -> Chat -> back navigation closes app

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1470]
weird stuff with the navigation, reported by an external user. confirmed. Instead of closing the app, this should clearly navigate back to the spaces->chat-page.

**Comment by gtalha07** [comment]
@gnunicorn We still seeing this issue? If yes, can you share screenshot video of this flow ?

**Comment by gnunicorn** [comment]
@gtalha07 yes, this still happens. I have a screenrecording if you want (but it contains personal data, so I won't post it). Important to note is that with `back`, I mean the `back` action/key/motion of android not the `<` on the top left. That arrow seems to be working fine, just the back action closes the app.
