### ISSUE TITLE
Localisation: for time picking and showing

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1474]

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
CC : @gnunicorn 
- - -
I have check regarding this point with Localisation implementation. I believe this point will be covered when we work on the #1334.
- - -
Demo work:
- I have added below languages in i18n.dart
![Screenshot 2024-03-05 at 1 48 31 PM](https://github.com/acterglobal/a3/assets/51526480/428c476f-7bf0-440f-a3c1-43cd39433c39)
- And this is how time picker looks with 12-hours format and 24-hours format.

![12 Hours](https://github.com/acterglobal/a3/assets/51526480/dbf3583d-8c31-49ba-95af-2f90f767895e)

![24 Hours](https://github.com/acterglobal/a3/assets/51526480/77f7ab7a-1599-4664-895f-7255a8026e09)

**Comment by kumarpalsinh25** [comment]
@emilvincentz 
CC : @gnunicorn 

I have tested with latest nightly build. Our new Time pickers already works with system settings of the hours format. Please check below screenshots of the my iPhone.

![12 Hour](https://github.com/acterglobal/a3/assets/51526480/71a47c87-a9f5-4646-8878-4c4d0abb9204)
![24 Hour](https://github.com/acterglobal/a3/assets/51526480/4839d75b-ddf5-45e2-9abc-bdfbbab717e7)

**Comment by emilvincentz** [comment]
nice! will test out when I can:)

**Comment by gnunicorn** [comment]
closing as already-fixed then. Please re-open if found to be other.
