### ISSUE TITLE
Pins Create and Edit: make URL optional

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1499]
1. Wanted to add an image as pin, but cant create until i have added an url, which i dont need. 
Fix: remove the required URL

2. When creating the pin with image, i can not click to see the image. 

![Image](https://github.com/acterglobal/a3/assets/77483554/22f68728-935c-4d2b-920a-c9e7bba5cc7b)

**Comment by gnunicorn** [comment]
URLs are optional, if you have a description. But arguably, now that we have attachments, we might not need either to be present...

**Comment by emilvincentz** [comment]
yeah i really dont think that makes sense to have that required
