### ISSUE TITLE
Suddenly logged out on IOS

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1541]
Suddenly just logged out on IOS. Happened twice today.

However i still get push notifications

**Comment by emilvincentz** [comment]
This continues to happen

**Comment by kumarpalsinh25** [comment]
@gtalha07 @gnunicorn 
I believe this is issue and issue number #1422 are relevant and may be due to `flutter_secure_storage`.

**Comment by gnunicorn** [comment]
@kumarpalsinh25 I concurn. This could very well be the same issue indeed and I, too, suspect `flutter_secure_storage` and changes that might have happened on Apple in the keychain service in recent months ...

**Comment by emilvincentz** [comment]
at least on the iOS, it seems that this bug has replaced the IOS error 1, so currently it seems pretty linked together

**Comment by emilvincentz** [comment]
this just happened again unfortunelty. 
In IOs and on the latest app store release.

**Comment by emilvincentz** [comment]
Maybe linked to verification issue #202 (a3-meta)
