### ISSUE TITLE
Dual scroll bars in chat room

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#1563]
We can see dual scroll bars in chat room on windows desktop.
![image](https://github.com/acterglobal/a3/assets/48786056/2818c494-6454-4c36-b471-4d73b9465430)
Outer scroll bar seems to be removed.

**Comment by gnunicorn** [comment]
this is how it is supposed to be, no? The outer is the scrollbar and the smaller is the position indicator ...
