### ISSUE TITLE
Implement empty state for sub spaces page

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1592]
@MirekKolaja @kokodavid when you have design for this, then you can put it here.

Also cover, how it looks for admin and members who has different permission settings.

![grafik](https://github.com/acterglobal/a3/assets/40496/c8f46a7c-7722-4e28-bdff-ce0e3920023d)

**Comment by emilvincentz** [comment]
Currently it look like this

[Skindergades.pdf](https://github.com/acterglobal/a3/files/14903623/Skindergades.pdf)

**Comment by kokodavid** [comment]
https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=9177-9105&mode=design&t=RLhkK16PdZFnnw1w-4




![Image](https://github.com/acterglobal/a3/assets/47295684/33123b00-0d00-47f6-a0bf-87a8c56e6cba)

**Comment by gnunicorn** [comment]
fixed in #1727 .
