### ISSUE TITLE
decryption error

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1608]
This errror is getting more persistent and really blocker.

![Image](https://github.com/acterglobal/a3/assets/77483554/c91efda2-2678-4757-ab83-3d9308647f79)

**Comment by gnunicorn** [comment]
same as https://github.com/acterglobal/a3-meta/issues/145

**Comment by gnunicorn** [comment]
let's upgrade latest matrix, so we https://github.com/matrix-org/matrix-rust-sdk/issues/3110

**Comment by gnunicorn** [comment]
upgrade done and merged. let's see if this still appears. @emilvincentz please re-login if you see this after the next nightly and if you see it again, please provide the logs if you see it again!
