### ISSUE TITLE
change language from "kick user" to something else.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1635]
A small thing, but something that several has pointed out.
Especially groups who work with ending violence and human right crimes dont like it. Understandable.

Suggestion:
"Remove user"

**Comment by Archiewiz** [comment]
Hi, thinking these maybe better:

Good bye user or bye user (from a gratitude mindset wishing user leaving good bye)
End user 
Detach user
Out user (as in/out)
Off board user
Zero user (signifying end)

**Comment by gnunicorn** [comment]
it has been done already "remove user"
