### ISSUE TITLE
FAtal error (platform exeption)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1636]
Several user repporting this, upon opening the app the first time.
I believe its mostly for Android users, but not sure.
![Image](https://github.com/acterglobal/a3/assets/77483554/6945607f-5399-4aec-b667-de440ae22bed)

**Comment by emilvincentz** [comment]
@gnunicorn couldnt see a status on this one, so created the issue here.
Or has it already been fixed?

**Comment by gnunicorn** [comment]
this is an old release. At least more than a week old. Please ask them to upgrade and in the new one, they can copy the stacktrace. Also, this is iOS (not android) on an old (and not by apple supported anymore) iOS 15, which is fixed [by this already](https://github.com/acterglobal/a3/pull/1629) . Closing as fixed, feel free to reopen if that still occurs after this weeks release (will be `1.24.3418`).
