### ISSUE TITLE
Hard to close user profile, as the drawer goes all the way to the top

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1650]
https://github.com/acterglobal/a3/assets/77483554/734456f8-5360-445b-a4ef-cdfbb47509aa

**Comment by gnunicorn** [comment]
from my understanding you need to use the drawer puller and pull from there... but I agree, on a small screen with it full screen, this isn't particuarly easy ...


https://github.com/acterglobal/a3/assets/40496/3e04399c-9d5a-45e5-8eb1-1e8ff8204a04
