### ISSUE TITLE
Can not  view files/pdf's in acter chat

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1663]
there are several options to share, but not to view or download.

![Image](https://github.com/acterglobal/a3/assets/77483554/07f68abb-5bec-4bc4-804c-9147d172ed96)

**Comment by emilvincentz** [comment]
Also reported by Youth4Parliament users

**Comment by gnunicorn** [comment]
maybe https://pub.dev/packages/pdfx can do this for us?
