### ISSUE TITLE
Flatpak libmpv.so.1 not found

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1665]
Trying to start the latest flatpak installable build, nothing happens. Starting it from the commandline I see:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=acter global.acter.a3
acter: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

``

**Comment by maxwell-kalin** [comment]
yep, have this issue on Fedora 40, the flatpak is unusable

**Comment by 0cwa** [comment]
This also effects the Linux .tar release

**Comment by gnunicorn** [comment]
@0cwa as it is an external library we won't be packaging libmpv ... for the tar release you probably need to install libmpv via your distro's package manager... e.g `apt install mpv` or `pamac install libmpv`

**Comment by 0cwa** [comment]
I'm on fedora: I've already tried installing `mpv` `mpv-libs` `mpvqt` `mpvqt-devel` and `mpv-libs-devel` and then restarting my shell.  I don't see anything else relevant in the package index either

**Comment by gnunicorn** [comment]
hmm... that's odd.. @0cwa have you tried [this hack for fedora when libmpv isn't found](https://github.com/flet-dev/flet/issues/2823#issuecomment-2242151270) ? Would be good to know whether that is fixing it ...

**Comment by 0cwa** [comment]
That works, thanks!

**Comment by gnunicorn** [comment]
flatpak support has always been wonky and from the current perspective we will probably not resurrect that. We might investigate supporting more distros directly, but flatpak just doesn't feel like the good way to distribute to users.
