### ISSUE TITLE
description field when creating task list, does not appaer

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1669]

**Comment by emilvincentz** [comment]
I mean this field @gnunicorn 
<img width="617" alt="Screenshot 2024-04-24 at 09 50 40" src="https://github.com/acterglobal/a3/assets/77483554/d18ed77c-e8e9-4520-aa9b-30b98dfa07af">

**Comment by gnunicorn** [comment]
my mistake, I misread the "task list" as "task".
