### ISSUE TITLE
Blob from text editor shows

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1679]
Not sure when this happens, but I have experienced it a couple of times.

https://github.com/acterglobal/a3/assets/77483554/b72454bf-ca72-4c5c-89c8-c6a7a1acae4b

**Comment by gnunicorn** [comment]
@emilvincentz only in chat or have you seen this elsewhere as well?

**Comment by emilvincentz** [comment]
no mainly stemming from chat, but then gets stuck also on other screens

**Comment by gnunicorn** [comment]
can confirm this error on android as well. even able to create two of them:
![1000022372](https://github.com/acterglobal/a3/assets/40496/3d89bbf8-9cdf-4292-bf91-c9bc06316fe3)

![1000022373](https://github.com/acterglobal/a3/assets/40496/afb6ead7-16b3-4f8e-9868-12cc92a1dca6)

**Comment by emilvincentz** [comment]
just happened again on nighlty from this morning 


![Image](https://github.com/acterglobal/a3/assets/77483554/3e447552-e065-4bdb-a642-cb76a2db4157)
