### ISSUE TITLE
Error loading room/space, too many files open

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1682]

**Comment by emilvincentz** [comment]
Happens when i open the app for the first time after logging in. 
If i close the app and reopen, it loads.


![Image](https://github.com/acterglobal/a3/assets/77483554/3b108206-201e-40a4-adaf-bbbf60688dab)

**Comment by gnunicorn** [comment]
lowering the urgency as this is most likely a power-user-problem ... but yeah, the fact that we have too many files open for a macos system to error on us is suspicious...

**Comment by bitfriend** [comment]
I think [Limit concurrent HTTP requests](https://github.com/acterglobal/a3/pull/1898) may fix this issue.

**Comment by gnunicorn** [comment]
true. haven't seen it since. closing.
