### ISSUE TITLE
Accepting chat invite or space invite, doesnt direct user to the accepted chat/space

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1686]
The problem with this, is that you accept the chat/space and want to afterwards view it. But you dont always remember the name of the chat /space. Also as the chat doesnt always appear on the top.
Ive observed user clicking on the accept button, and then response being "oh, where did it go?"
As such we should direct the user to the accepted chat/space. the same as on creating a space or chat.

**Comment by kumarpalsinh25** [comment]
https://github.com/acterglobal/a3/assets/51526480/d669f911-02b6-4f17-a7a4-782722226af0

**Comment by gnunicorn** [comment]
@kumarpalsinh25 https://github.com/acterglobal/a3/blob/cc40faff170d9360c15434d9a7ca3af1a6907cbe/native/acter/api.rsh#L2428 .
