### ISSUE TITLE
Events does not show in cronological order

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1697]

**Comment by gnunicorn** [comment]
where? it does on the dashboard ...

**Comment by emilvincentz** [comment]
only "preview" does.
if you click "se all events" it doesnt.

**Comment by emilvincentz** [comment]
![IMG_0483](https://github.com/acterglobal/a3/assets/77483554/bf07a0a8-e8f0-44f6-8cfd-683dd5e994d3)
