### ISSUE TITLE
Chat fixes

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1709]
high Priority 
 - [ ] #1732
- [ ] Preview is still shown of Acterglobla when mentioning user (pic 2), #1604
- [ ] Grey screen when mentioning user (pic3)

Lower:
- [ ] #1731
- [ ] When mentioning user, it also shows username, should only show display name (pic6)
- [ ] emoji icon white background? [#205](https://github.com/acterglobal/a3-meta/issues/205)

**Comment by emilvincentz** [comment]
Hey @gtalha07 any updates on grey screen when mentioning user? and acter.global preview after mentioning user?
I have tried to split the isssues, to help with prioritisaiton.

**Comment by gnunicorn** [comment]
I took the invite out of the tracking of this issue as we are dealing with that in separate part of the work.

Ref https://github.com/acterglobal/a3/issues/1731
