### ISSUE TITLE
MacOS app get's logout

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1713]
https://github.com/acterglobal/a3/assets/51526480/254a7999-7597-47d9-9e6e-552377fff74b

**Comment by gnunicorn** [comment]
fixed by #1707

**Comment by kumarpalsinh25** [comment]
> fixed by #1707


Actually, after #1707 this issue is generated.

**Comment by gnunicorn** [comment]
it is a one-time thing after the new code was activated and unfortunately there was no way for us to prevent this or inform the user... but it is gone now.
