### ISSUE TITLE
Visibility and Accessibility APIs

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#1721]

**Comment by gnunicorn** [comment]
I am not clear what is missing:
- [`Space.isPublic`](https://dev.acter.global/api/main/dart-sdk/acter/Space/isPublic.html) shows whether the space is `public` or `private`
- [`Convo.isEncrypted`](https://dev.acter.global/api/main/dart-sdk/acter/Convo/isEncrypted.html) and [`Space.isEncrypted`](https://dev.acter.global/api/main/dart-sdk/acter/Space/isEncrypted.html) indicate whether it is encrypted
- `.joinRuleStr` gives you the info about which join rule is being used (it is already being used afaik)

Setting the join rule we have the [`JoinRuleBuilder`](https://dev.acter.global/api/main/dart-sdk/acter/JoinRuleBuilder-class.html), which you get from the [the api directly with `newJoinRuleBuilder`](https://dev.acter.global/api/main/dart-sdk/acter/Api/newJoinRuleBuilder.html) and then pass to [`room.setJoinRule`](https://dev.acter.global/api/main/dart-sdk/acter/Room/setJoinRule.html) once you have fully set it up.

With the latter you can set the join rule simply by doing `builder.joinRule(str)` where `str` is any of of:
`private`, `public`, `invite`, `knock`, `restricted` or `knock_restricted`. Public marks it as public. the `restricted` ones do use the provided `addRooms` to limit to membership from those rooms.

I think this is all that is needed. Anything we are missing for #1379 , @kumarpalsinh25 ?

**Comment by kumarpalsinh25** [comment]
> I think this is all that is needed. Anything we are missing for #1379 , @kumarpalsinh25 ?

I think this should be sufficient. Still if need anything then I will update you. Thanks.
