### ISSUE TITLE
MacOS opens with black screen

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1728]

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/001b08a5-e0af-4bb0-9df6-62aec6af5270)

**Comment by gnunicorn** [comment]
can you start it from the commandline and paste the output here please?!?

**Comment by emilvincentz** [comment]
@gnunicorn 
Last login: Sun May 12 17:05:14 on ttys000
/Applications/Acter.app/Contents/MacOS/Acter ; exit;
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter ; exit;
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553128788720 ; len: 33
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: expected value at line 1 column 1

2024-05-12 17:05:35.474 Acter[35593:1673430] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

**Comment by gnunicorn** [comment]
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: expected value at line 1 column 1


now that is bad.

**Comment by emilvincentz** [comment]
Logs from trying to:
1. run the app from the command line to overwrite the log settings by running /Applications/Acter.app/Contents/MacOS/Acter settings set rust-log trace
2. run the app again from the command line and copy-paste the output into the issue . it might be a lot ...

Last login: Thu May 23 16:20:16 on ttys000
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter settings set rust-log trace
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Option key is mandatory.
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 34766, tid: 6125481984, name io.flutter.ui
os: macos arch: arm64 comp: no sim: no
build_id: 'b09aafd842763feab274505d08c78f21'
isolate_dso_base: 11687c000, vm_dso_base: 11687c000
isolate_instructions: 1168888c0, vm_instructions: 11687e580
    #00 abs 0000000116fbf3bb _kDartIsolateSnapshotInstructions+0x736afb
    #01 abs 000000011717c8bb _kDartIsolateSnapshotInstructions+0x8f3ffb
    #02 abs 00000001171b9f1f _kDartIsolateSnapshotInstructions+0x93165f
    #03 abs 00000001170ce153 _kDartIsolateSnapshotInstructions+0x845893
    #04 abs 0000000117156a87 _kDartIsolateSnapshotInstructions+0x8ce1c7
    #05 abs 00000001170ce0ff _kDartIsolateSnapshotInstructions+0x84583f
    #06 abs 00000001171b9b4b _kDartIsolateSnapshotInstructions+0x93128b
    #07 abs 00000001171b9173 _kDartIsolateSnapshotInstructions+0x9308b3
    #08 abs 00000001170d260b _kDartIsolateSnapshotInstructions+0x849d4b
    #09 abs 00000001168ae66f _kDartIsolateSnapshotInstructions+0x25daf
    #10 abs 00000001171bcbeb _kDartIsolateSnapshotInstructions+0x93432b
    #11 abs 00000001170d2b93 _kDartIsolateSnapshotInstructions+0x84a2d3
    #12 abs 00000001171bc943 _kDartIsolateSnapshotInstructions+0x934083
    #13 abs 000000011689df2f _kDartIsolateSnapshotInstructions+0x1566f

2024-05-29 13:37:43.621 Acter[34766:1947938] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
/Applications/Acter.app/Contents/MacOS/Acter
/Applications/Acter.app/Contents/MacOS/Acter
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553147588704 ; len: 33
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: expected value at line 1 column 1

emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553180483456 ; len: 33
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: expected value at line 1 column 1

zsh: terminated  /Applications/Acter.app/Contents/MacOS/Acter
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553161669008 ; len: 33
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: expected value at line 1 column 1

2024-05-29 14:17:15.555 Acter[35063:1966847] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

@gnunicorn

**Comment by gnunicorn** [comment]
resolved with #1830 .
