### ISSUE TITLE
Typos in onboarding

### ISSUE THREAD

**Issue by MirekKolaja** [acterglobal/a3#1741]
Correct typos in onboarding:

Have you saved your username?
- [ ] If you forget your password, **YORE** -> change the whole sentence to -> Your username is crucial for password resets.

Registration

- [ ] By clicking to create **CROFILE**, you agree to our Terms & Conditions and Privacy Policy > change the whole sentence to -> By creating a profile, you agree to our Terms & Conditions and Privacy Policy.

![Image](https://github.com/acterglobal/a3/assets/42695916/7bc15a97-5c93-483f-8f66-58444d5fd692)
![Image](https://github.com/acterglobal/a3/assets/42695916/4ff7baf2-c3b9-4af0-bb4f-6e4a7f487617)

**Comment by gnunicorn** [comment]
fixed.
