### ISSUE TITLE
Home doesnt always work

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1754]
Dont know when it happens though, but saw it also happened for a user in the pilot.

https://github.com/acterglobal/a3/assets/77483554/7e18b401-81a3-4f71-828c-e2501c191e63

**Comment by gnunicorn** [comment]
can you share the logs of that session?

**Comment by emilvincentz** [comment]
will try to do next time

**Comment by gnunicorn** [comment]
just merged a change to simplify the state management of the navigation (#1767), but I couldn't clearly identify if that is fixing it as I was unable to find any reproducible case of it . I'll close this with the next release and if it happens again, please reopen it.

**Comment by gnunicorn** [comment]
finally saw this happen. only on the iphone though. this shows up in the console trying to tap the home button:
```
flutter: INFO: 2024-05-29 13:43:13.073972: restoring
[GoRouter] restoring

════════ Exception caught by foundation library ════════════════════════════════
Bad state: Cannot use origin without a scheme:
════════════════════════════════════════════════════════════════════════════════
```

**Comment by gnunicorn** [comment]
can't repro anymore on latest `main` with my iOS dev build. @emilvincentz please re-open and submit logs if this persists on latest nightly or release version from this week...!?!
