### ISSUE TITLE
When inviting user to join a space, it was stuck on loading, not sending out the invite

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1757]
Could it be that he newly signed up?  That the server needs to rexognize him?
Or could it be that i used his display name when searching? 

![Image](https://github.com/acterglobal/a3/assets/77483554/2138cca9-549b-4182-9d1a-21d5ad74c511)
![Image](https://github.com/acterglobal/a3/assets/77483554/5c1a6cfd-487e-43db-90ec-64d7b7c56818)

**Comment by gnunicorn** [comment]
you happen to have the logs of that sessions available somewhere?

**Comment by emilvincentz** [comment]
unfortunately no

**Comment by gnunicorn** [comment]
even upon a server timeout this should always close eventually ... we are catching all potentially errors... closing for now until we see this again. (also considering @kumarpalsinh25 is redoing this section ..)
