### ISSUE TITLE
Invite code doesnt add the right spaces/chats

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1758]
In the case of onboarding talanta africa (code: talanta), it didnt add the user to all the selected space. But it added the user to e.g. Acter.global space which isnt on the list. 
Could it be that i had added this space before, but then removed it? and it hasnt updated?
I have experienced before that the user doesnt get added to all the spaces/chats that is listed.

**Comment by gnunicorn** [comment]
already tracked in #1627 .
