### ISSUE TITLE
Error loading content + error on bug report

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1779]

**Comment by emilvincentz** [comment]
When tried to bug report, it also showed this error.

![Image](https://github.com/acterglobal/a3/assets/77483554/86ed137a-5417-4305-b590-5d3c01a6f543)
![Image](https://github.com/acterglobal/a3/assets/77483554/b9dfbf64-0c4d-494a-b79e-e599ad4b9e83)

**Comment by gnunicorn** [comment]
as both error messages say: you can't reach the servers. probably some connection failures on your end?!?

**Comment by gnunicorn** [comment]
We have better error displaying now.
