### ISSUE TITLE
When you delete a pin confirmation box stays too long, doesn't redirect correctly after

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1815]
within a space, it goes to your home section afterwards. It should stay on the space. 
Also, it the confirmation box keeps appearing until clicking "remove" again.

**Comment by gnunicorn** [comment]
that isn't consistent. if you removed the pin from a different place (e.g. your pins overview), switching to the space screen afterwards would be very confusing. Instead we probably want to go "back" to where we came from ...

**Comment by emilvincentz** [comment]
Also happens for events and space
