### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#183]
I found both `Name` and `Naam` exists in `app/lib/l10n/app_de.arb`.
I don't know German, but I guess some conflicts exist in German translation.

**Comment by HatimWayne** [comment]
This may be too late, but Name is German whereas Naam is Dutch.

**Comment by bitfriend** [comment]
Thank you for your notification.
Will apply it.

**Comment by HatimWayne** [comment]
I have made a pull request correcting all the mistakes in the translation file, hope it helps.
