### ISSUE TITLE
Remove bottom menu when entering chat

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1848]
No need to have it there, allowing for more space in the chat

![Image](https://github.com/acterglobal/a3/assets/77483554/583bde0a-2c70-4c5a-8d57-6b64be8495b7)

**Comment by gnunicorn** [comment]
I disagree and have adjusted the product assignment accordingly.

**Comment by gnunicorn** [comment]
this has been resolved in a different way.
