### ISSUE TITLE
Notifications show on home screen, even though no notifiations in Acter

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1862]
Several users reporting this.

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/4865e9d2-d9d8-4fb8-b79b-fb7097355c25)

![Image](https://github.com/acterglobal/a3/assets/77483554/6e3dfa05-2e47-44ae-8fc4-20e43a48d947)

**Comment by gnunicorn** [comment]
yeah, ios isn't properly resetting the counter for some reason.

**Comment by gnunicorn** [comment]
fixed
