### ISSUE TITLE
Invite all members from a space, does not work (shows 0 invited)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1895]
Also they do not figure under pending

https://github.com/acterglobal/a3/assets/77483554/592a3bc0-084d-42a7-ae7d-7a037a5f9110

**Comment by gnunicorn** [comment]
@emilvincentz video doesn't play here. refreshed several times, but it doesn't play with "no supported mime type found". is it possible this is some non-web Apple custom video format? Can you convert it to mp4?

**Comment by emilvincentz** [comment]
![image](https://github.com/acterglobal/a3/assets/77483554/32bafa84-28ae-4ca7-9794-7ab10942c791)

**Comment by emilvincentz** [comment]
does it work now @gnunicorn ?

https://github.com/acterglobal/a3/assets/77483554/581c7ada-fa01-4612-a323-b01f9ab0fd07

**Comment by gnunicorn** [comment]
Video still not working, no @emilvincentz .

**Comment by gnunicorn** [comment]
which version is that? and are you trying to invite to a space or a chat?
