### ISSUE TITLE
multi parent avatar bugs

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1900]
Avatar of space parent shows even though it’s a recommended space.
Also after removing the linkage, the avatar still shows.

**Comment by emilvincentz** [comment]
The avatar still shows, although the "mellemfolk aarhus" space is not listed under "den grønne ungdom.."


![Image](https://github.com/acterglobal/a3/assets/77483554/f9f0c0ca-ee25-4c98-be76-7e80d2908165)



![Image](https://github.com/acterglobal/a3/assets/77483554/99536dc3-ae56-4461-94f9-16e7d72b1216)

**Comment by emilvincentz** [comment]
@gtalha07

**Comment by gnunicorn** [comment]
> The avatar still shows, although the "mellemfolk aarhus" space is not listed under "den grønne ungdom.."

we are not removing the "parent" link in the lower space when "unlinking", I think... We currently don't have any UI to manage a parent list of a space ...
