### ISSUE TITLE
Selected chat does not show in the ui / colour

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1901]
right now on desktop there is no divide between the colours of the different sections, so i also dont know which chat i have selected

![Image](https://github.com/acterglobal/a3/assets/77483554/e053e023-263a-4ce0-b5f1-788eb5dfc492)

e.g. compared to element

![Image](https://github.com/acterglobal/a3/assets/77483554/d4afdc0f-84f3-496c-af57-9ddccf80229b)

**Comment by emilvincentz** [comment]
@kumarpalsinh25 just FYI after latest colour changes

**Comment by kumarpalsinh25** [comment]
I haven't tested much on the desktop. Thank @emilvincentz for notifying. This will be fixed.
Keep posted any UI glitches and assign it to me.

**Comment by gnunicorn** [comment]
fixed in #1903
