### ISSUE TITLE
Show parent in space

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1914]
in the upcoming design there is no way to know the details of what parents spaces exist or what other rooms people can join from. We want to do the following for those:

- when clicking the parent-avatars we want to show a bottom drawer with the list of those spaces (everywhere)
- when clicking the "limited" badge, we show a bottom drawer with the spaces whose members can join

**Comment by kumarpalsinh25** [comment]
Let's connect on call for this and finalised quickly.

**Comment by emilvincentz** [comment]
sounds good, ping me whenever:)
