### ISSUE TITLE
switch to using `ComposerDraft` from the matrix-sdk for chat message compsing (rather than riverpod)

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1924]
As one problem with the chat input field is clearly caused by our combination of riverpod provider and the controllers messing with each other, we might want to look at the [ComposerDraft the matrix-sdk people have recently introduced](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/struct.ComposerDraft.html#). This has the same function of allowing to keep the composing state of a chat message around when the user leaves the room, but with the additional advantage that it is also stored in the local database between restarts ... pretty neat!

**Comment by gtalha07** [comment]
Completed in #2056.
