### ISSUE TITLE
stuck on loading update section when opening the app

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1928]
I thought it was only me experiencing this, but then i had a look at a friends phone (Iphone SE) and now he also experiences this. 
Unfortunately he is not able to create a bug report. 

![Image](https://github.com/acterglobal/a3/assets/77483554/6c056961-5c81-49de-84ea-89a891f55e5a)

**Comment by emilvincentz** [comment]
After the latest nightly i dont exprience this issue anymore, where its stuck on loading update. 
However after loading it keeps freezing, forcing me to close and reopen the app.

**Comment by emilvincentz** [comment]
The situation on being stuck on the update, seems to have been fixed. However being replaced by the constant freexing issue.
https://github.com/acterglobal/a3-meta/issues/368

**Comment by emilvincentz** [comment]
Happens again. Im on nighlty from 11th July

**Comment by gnunicorn** [comment]
fixed in #1949
