### ISSUE TITLE
Random Avatar Issues

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1937]
There are random issues in avatar as below.

1) Weird avatar view:
![ima_9a9c164](https://github.com/acterglobal/a3/assets/51526480/6385fb2a-11db-445b-8b55-1945e8bb7bd8)

2) Wrong avatar showing:
![ima_2984c21](https://github.com/acterglobal/a3/assets/51526480/d6e793c1-76cf-4103-b7c6-358b2398ba63)

3) Avatar not loading at all:
![ima_e9c3703](https://github.com/acterglobal/a3/assets/51526480/6e240815-a90e-429f-b707-00f7494c65a2)

**Comment by gnunicorn** [comment]
@gtalha07 any ideas?
