### ISSUE TITLE
sub spaces show on desktop but not on mobile app

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1978]

**Comment by emilvincentz** [comment]
![Image](https://github.com/user-attachments/assets/ba3edc49-9622-4c4e-b4d1-7f9419cc2fe2)



![Image](https://github.com/user-attachments/assets/adf10d40-1e03-407d-aa59-a74355d061f9)

**Comment by gnunicorn** [comment]
is that still persistent after restarting the app and ensuring it has finished syncing?

**Comment by emilvincentz** [comment]
Restarted the app and seems to work again = appears on both devices

**Comment by gnunicorn** [comment]
then this is the known caching issue. we have no clear story as to when to refresh that listing ...
