### ISSUE TITLE
Clean up code periodically

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#198]
Here will perform the simple correction.
1. Remove the unnecessary code.
2. Correct the typo or wrong order.

**Comment by gtalha07** [comment]
Would like to add additional checks to maintain performance on UI side:
3. Replace Stateful Widgets with Stateless which are not using state.
4. Refactor long methods or extract widgets where possible.
5. Refactor widgets with Reusable where possible.

**Comment by bitfriend** [comment]
Important discovery.
Agree with you.

**Comment by bitfriend** [comment]
Replace `EdgeInsets.only()` that has 3+ fields with `EdgeInsets.fromLTRB()`.

**Comment by bitfriend** [comment]
Reduce lines as much as possible.
For example, replace
```dart
    EdgeInsets dateDividerMargin = const EdgeInsets.only(
      bottom: 32,
      top: 16,
    ),
```
with
```dart
    EdgeInsets dateDividerMargin = const EdgeInsets.only(bottom: 32, top: 16),
```
