### ISSUE TITLE
When clicking pin link, it open edit modal instead of directing to link. Even if you are not admin of the space or created the pin.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1985]

**Comment by emilvincentz** [comment]
@kumarpalsinh25 
We need to not allow people to edit pins that they did not create, unless you are space admin
Also we need to find better ways to click the pin, that does not open the editer.

**Comment by gnunicorn** [comment]
> We need to not allow people to edit pins that they did not create, unless you are space admin

you can configure the necessary permission level in the settings per space. By default everyone can create, edit and delete pins (as we assume a space to be a peer-to-peer place).

**Comment by emilvincentz** [comment]
I see, thanks @gnunicorn 

But @kumarpalsinh25 we still need a better way of clicking the links in a pin.
Right now you need to be very careful in clicking the arrow, otherwise it opens the link editor

**Comment by kumarpalsinh25** [comment]
> I see, thanks @gnunicorn
> 
> But @kumarpalsinh25 we still need a better way of clicking the links in a pin. Right now you need to be very careful in clicking the arrow, otherwise it opens the link editor

Let me see what can be done here to improve UX in this case.
