### ISSUE TITLE
Chat Attachments are not working

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1999]
After recent router related PR, chat attachment dialog gets close and but not able to post any attachment.

https://github.com/user-attachments/assets/5bbd3f55-b593-4caf-90a3-d7aea4ddc4b5

**Comment by gnunicorn** [comment]
any logs or messages in the console?

**Comment by kumarpalsinh25** [comment]
No logs or message. I play around it a bit with Navigation and Context and it works sometimes. Not sure about exact use-case.
