### ISSUE TITLE
text after mention is marked as mention

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#2021]
See image below

**Comment by emilvincentz** [comment]
This is if you forget to make a space after the mention

**Comment by gtalha07** [comment]
@gnunicorn It seems like the regex approach isn't quite working here. And I would like to switch this to a more correct and safe pattern which would require keeping various methods to track input controller selection and only style valid mention data. It's a long-shot though...

**Comment by gnunicorn** [comment]
may I suggest to put the logic for identifying the part into a separate function and have many, many unit tests for all cases we know of ... so we can extend that library with missing cases over time and just increase its robustness...
