### ISSUE TITLE
selecting text doesn't work in chat editor

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2040]
I can't move the cursor for dome reason:

https://github.com/user-attachments/assets/76953857-4e4c-4d85-a7b2-839908480c69

**Comment by gtalha07** [comment]
@gnunicorn I've tried reproducing this case, both on iOS and android. It seems to move cursor correctly when tapping sub-parts. See the video recording:

https://github.com/user-attachments/assets/d31cb7b3-8b99-42ec-be9a-4b0172a3c880

However, I seem to discover another bug, which keeps shifting cursor to end of text as you can see in video. That shouldn't happen...

**Comment by gnunicorn** [comment]
@gtalha07 that was on the last release from last week. maybe your recent changes already fixed that? I will try again with the latest release from today.

**Comment by gnunicorn** [comment]
It's fixed in the latest release from today
