### ISSUE TITLE
Edit message bugs + line jump

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#2049]
When you swipe to edit message, the old text is not displayed in editor.

Also, when re-editing the message, the initial message is shown. See video below.

Lastly, jump to new line to make a paragraph does not show properly. 
Eg. Typing this:
Line 1
Line 2 

Line 4

Is shown like this:

Line 1
Line 2 
Line 4

https://github.com/user-attachments/assets/08106dd9-eac7-4f92-8abf-431f9efcb0db

**Comment by emilvincentz** [comment]
@Talha think this happened after latest chat changes. 
Tested on latest flight version (from today)

@gtalha07

**Comment by gtalha07** [comment]
@emilvincentz Yes, I seem to have encountered these errors. Will send a group fixes PR soon!

**Comment by emilvincentz** [comment]
Awesome Talha

These two might also be related

https://github.com/acterglobal/a3-meta/issues/457https://github.com/acterglobal/a3-meta/issues/456

**Comment by emilvincentz** [comment]
Awesome Talha

These two might also be related

https://github.com/acterglobal/a3-meta/issues/456
https://github.com/acterglobal/a3-meta/issues/457
