### ISSUE TITLE
Cant edit a message; chats cursor jumps to the end of the message

### ISSUE THREAD

**Issue by jo-acter** [acterglobal/a3#2084]
When editing a chat message, it's impossible to edit the message after, as the cursor always jumps to the end of the message after every added character.

This is experienced by using Windows desktop version.

**Comment by gtalha07** [comment]
@jo-acter It's believed to be fixed [here](https://github.com/acterglobal/a3/pull/2069). Are you sure it's still exists in latest nightly/release?

**Comment by jo-acter** [comment]
Hi! I had this issue still yesterday. I will do some testing let you know if the issue persists!

**Comment by gnunicorn** [comment]
the merge was only done after the last release. @jo-acter check again with the release coming out today?!?

**Comment by jo-acter** [comment]
Ok, I will!

**Comment by gnunicorn** [comment]
waiting to confirm if that persists on the latest version.
