### ISSUE TITLE
Text input field in chat is very narrow.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#2095]
With both the message icon, file upload icon, security shield icons and emoji icon, only half of the width is left to see what you're actually typing. 

Suggestion:
Remove the shield icon upon typing 
Remove the emoji icon on mobile.
(At least on iOS no other apps as far as I know is showing the emoji icon, as the keyboard already has emojis) ref to signal

![image](https://github.com/user-attachments/assets/953d95c9-c06b-4ddb-9b66-88c378effda2)

**Comment by emilvincentz** [comment]
What do you think about this @kumarpalsinh25 ?

**Comment by kumarpalsinh25** [comment]
> What do you think about this @kumarpalsinh25 ?

Yes it looks bit narrow due to encryption status icons. Here is my suggestions.

![Chat Input](https://github.com/user-attachments/assets/6cd91803-ad42-4423-a209-87935b1f255c)

**Comment by emilvincentz** [comment]
Looks much better and with more space.
But do we really need the emoji icon? Dont most users have emojis in their keyboard? 
At least that is what I use, as the current Acter emoji selector and emoji search  isn't the best atm. anyway

**Comment by kumarpalsinh25** [comment]
> Looks much better and with more space. But do we really need the emoji icon? Dont most users have emojis in their keyboard? At least that is what I use, as the current Acter emoji selector and emoji search isn't the best atm. anyway

Yes agree. Emoji selector will be useful when we have other options like sticker, custom emoji etc.. Simple emojis are now provided as default on android and iOS keyboards.

**Comment by emilvincentz** [comment]
Cool!

**Comment by gnunicorn** [comment]
> But do we really need the emoji icon? Dont most users have emojis in their keyboard?

We do still need it for Desktop for sure.

>  Simple emojis are now provided as default on android and iOS keyboards.

How far back does support for that go? And can we be sure about that for all Android OS it will be there? We have people running some pretty old Androids.


WhatsApp and Signal both provided that button on my (very recent) Android:
![image](https://github.com/user-attachments/assets/691aaa56-3396-4f7d-8613-62cab8935935)
![image](https://github.com/user-attachments/assets/f1f1df8e-79d8-4e56-b411-6e937e88acc6)

Once you started typing, they make the thing more dense and remove items - which I think we should also be doing:
![image](https://github.com/user-attachments/assets/09ae2a91-3144-4055-b6ee-45659916c5f7)
![image](https://github.com/user-attachments/assets/cc315f2f-d8be-4186-b4f3-1dad2e846e9e)


However, the emoji icon stays visible at all times.


---

I don't really think we need the encrypted icon ... UNLESS we are in an unencrypted chat, in that case we should show a red encryption-not-enabled-icon maybe?
