### ISSUE TITLE
Make obligatory space selection more visible

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#2192]

**Comment by emilvincentz** [comment]
It kept saying this error when i create an pin and coudlnt understand why until i noticed i hadnt selected a space.
Either the error message needs to be more clear and or the fact that you need to select a sapce (maybe both)

![Image](https://github.com/user-attachments/assets/8ea1b455-be99-458d-843d-a91ff9414e41)

**Comment by gnunicorn** [comment]
> Either the error message needs to be more clear and or the fact that you need to select a sapce (maybe both)

we could also just open the space selector to make them select a space and only show the error if they didn't do that ... then it becomes more obvious, too.

**Comment by gnunicorn** [comment]
fixed with https://github.com/acterglobal/a3/pull/2217
