### ISSUE TITLE
Unable to create update in space because feature disabled

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#2219]

**Comment by emilvincentz** [comment]
Wanted to create an update and attach to space. However it was grayd out so couldnt select. 
Then i remember it maybe was because it wasnt enabled. And i was correct, it was set to "none".
However i think as an admin, it should by default be on as it was in the past, right?

**Comment by gnunicorn** [comment]
> 
However i think as an admin, it should by default be on as it was in the past, right?

No, an admin should be offered to do it and then be asked if they want this feature enabled, as we do with all others as well.
