### ISSUE TITLE
Shows private spaces in space -> space listing

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2234]
even under "uncatogorized", these should not be showing up:

![image](https://github.com/user-attachments/assets/768b921f-fed2-491a-a639-361975f00649)

**Comment by emilvincentz** [comment]
<img width="1317" alt="Screenshot 2024-10-08 at 22 28 03" src="https://github.com/user-attachments/assets/f9cff6a3-92ef-487e-ade8-1c5bc301d052">

**Comment by emilvincentz** [comment]
<img width="1310" alt="Screenshot 2024-10-08 at 22 29 06" src="https://github.com/user-attachments/assets/c4d53259-3a29-494e-b62c-86316f1aaabc">
