### ISSUE TITLE
Swiping Boost Slides difficult on desktop 

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2358]
Reported in https://github.com/acterglobal/a3-meta/issues/626 :
> I can't swipe to see other slides on the boosts when I am on desktop version. 

I think this is due to the system using "vertical scroll" to "swipe" on desktop and that simply isn't always available for nice. So maybe some touch-swipe and/or click on the indicators would be useful?!?

**Comment by kumarpalsinh25** [comment]
@gnunicorn @jo-acter 

Swipe works fine on desktop as well. Check below video for reference.
https://github.com/user-attachments/assets/b3fcb89e-1bc4-4c5e-9809-ae7dd6896cfa

Default Behaviour is as below.

1) TrackPad : 
- Swipe Up-Down for vertical scrolling
- Swipe Left-Right for horizontal scrolling

2) Mouse :
- Scroll wheel Up-Down for vertical scrolling
- Scroll wheel Up-Down with Shift Key pressed for horizontal scrolling

I will check for additional alternate options for till that time you can go with above behaviour and let me know in case of any difficulties.

**Comment by gnunicorn** [comment]
> I will check for additional alternate options for till that time you can go with above behaviour and let me know in case of any difficulties.

being able to hold and drag with the mouse would be useful regardless, I think ... shift-scroll isn't really that commonly used by regular people, I believe...

**Comment by kumarpalsinh25** [comment]
> being able to hold and drag with the mouse would be useful regardless, I think ... shift-scroll isn't really that commonly used by regular people, I believe...

Yeh true and agree with you, I will look for better approach but just post here current behaviour for knowledge purpose. :)
