### ISSUE TITLE
Confusing zoom-in animation when switching chats

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#2429]
Select any chat in the list on desktop and you'll see a confusing zoom in animation of the same page... even if you select the same one again...

https://github.com/user-attachments/assets/ce95db09-eee6-40a3-b207-26542091cf4a

**Comment by kumarpalsinh25** [comment]
Mac Desktop App : Dev Mode: Reference
---

https://github.com/user-attachments/assets/6490abdf-017c-45fa-9e87-cbc279dd641c
