### ISSUE TITLE
 Image Messages preview bug.

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#258]
**Image messages in chat can't be previewed. It throws invalid path error.** 
![Screenshot_1664456113](https://user-images.githubusercontent.com/68579938/193037293-560db1d9-a9fc-4df2-8448-e396f65af2a7.png)
![image](https://user-images.githubusercontent.com/68579938/193037311-34ffe67a-aae8-49d2-81b2-8eb12e8a197b.png)

Images should get previewed correctly.

**Comment by kumarpalsinh25** [comment]
@gtalha07 
Is this issue is still persists? Can you check and confirm?

**Comment by gtalha07** [comment]
Closing as completed in #1232.
