### ISSUE TITLE
Double-tap = like

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#304]
When the user double taps a news item, a like-animation should show and the like counter should increase by 1.

**Comment by bitfriend** [comment]
I found matrix rust sdk implemented `m.sticker` event for `like` feature.
Will implement rust side soon.

**Comment by gnunicorn** [comment]
This seems to work here on latest `main` on macosx now. Though the animation is not right at the mouse cursor, it is pretty and visible...
