### ISSUE TITLE
Invite Message Component.

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#316]
Chat messages are currently composed of three types of message: Text, Image, File. We want to have invite component message in the chat which can be sent and recieved in a conversation. ```flutter_chat_ui``` provides the support of [CustomMessage](https://pub.dev/documentation/flutter_chat_types/latest/flutter_chat_types/CustomMessage-class.html) which can be used to make this component.
![image](https://user-images.githubusercontent.com/68579938/198050047-9b65138e-a7f6-4337-b217-a7c8b8cd14d8.png)

**Comment by gnunicorn** [comment]
Invites aren't part of a room (as they refer to a different room). What is the rational to show them in a specific conversation? Just because the inviter is in that room, too? That might mean we show them in a lot of rooms?!?

**Comment by gtalha07** [comment]
> Invites aren't part of a room (as they refer to a different room). What is the rational to show them in a specific conversation? Just because the inviter is in that room, too? That might mean we show them in a lot of rooms?!?

According to my understanding, invites are linked with the inviter and can share the link in joined conversations via copying the conversation link and pasting them. Matrix group links are tagged with ```#room-name.domain``` which we can use with regex to render invitation component instead.

**Comment by sachintha-s** [comment]
> > Invites aren't part of a room (as they refer to a different room). What is the rational to show them in a specific conversation? Just because the inviter is in that room, too? That might mean we show them in a lot of rooms?!?
> 
> According to my understanding, invites are linked with the inviter and can share the link in joined conversations via copying the invite link and pasting them. Matrix group links are tagged with `#room-name.domain` which we can use with regex to render invitation component instead.

@gtalha07  Does this mean we don't use invite data (`List<Invitation> invitations = [];`), and, we extract invite links from text messages and show this component instead of the invite link?

**Comment by gtalha07** [comment]
> > > Invites aren't part of a room (as they refer to a different room). What is the rational to show them in a specific conversation? Just because the inviter is in that room, too? That might mean we show them in a lot of rooms?!?
> > 
> > 
> > According to my understanding, invites are linked with the inviter and can share the link in joined conversations via copying the invite link and pasting them. Matrix group links are tagged with `#room-name.domain` which we can use with regex to render invitation component instead.
> 
> @gtalha07 Does this mean we don't use invite data (`List<Invitation> invitations = [];`), and, we extract invite links from text messages and show this component instead of the invite link?

Precisely, invite links are just links that anyone can share in any room. If shared in a conversation, it should render component instead. The invitation list data is for different goal .i.e. to serve as notifications and for inviting someone personally.
