### ISSUE TITLE
Tasks Screens

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#34]
We want to start with a simple ToDo-List/Task-Manager in the App. Feature brain-dump and moodboard: https://miro.com/app/board/uXjVOHP0484=/?invite_link_id=954661261852

**Comment by kokodavid** [comment]
Designs for Tasks Feature are currently in progress and they are available here and I'll be updating them as we continue .
https://www.figma.com/file/Bua5ifrK6H3LFYBXVFPQ5w/eFFEKTIO?node-id=114%3A1103

**Comment by kokodavid** [comment]
Tasks complete at the moment 
1. Activity /task done
2. Activity/Task detail view
3. #Tags
4. Likes and reactions
5. comments and files

**Comment by gnunicorn** [comment]
Let's integrate the screens into the UI for the demo version. We need:

expanded list:

![Image](https://user-images.githubusercontent.com/40496/198036171-8f479b33-a14c-48b7-a6a5-b6086dc6b136.png)

collapsed:


![Image](https://user-images.githubusercontent.com/40496/198036022-f7524442-84c1-466e-bbe4-187deba90242.png)

and todo-details upon click on todo:


![Image](https://user-images.githubusercontent.com/40496/198036541-e4d33a9c-3aaa-4572-9d97-8d486444c1c8.png)



![Image](https://user-images.githubusercontent.com/40496/198036589-fac948b4-6329-48cf-b136-605935753377.png)

**Comment by gtalha07** [comment]
@gnunicorn The mocked version is already in there #223.
