### ISSUE TITLE
 Not all emoji reactions get fetched from API.

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#403]
Emoji reactions keys only show upto 5 per message. The API give only 5 maximum reaction keys. This should not be limited.

**Comment by bitfriend** [comment]
It seems to be `matrix-sdk`-level limit.
I opened issue at `matrix-rust-sdk` repo.
https://github.com/matrix-org/matrix-rust-sdk/issues/1311
When they reply, I will implement code in according to it.
