### ISSUE TITLE
news image glitching: reverse colors

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#456]
When resizing my linux desktop effektio app from widescreen to portrait mode, it often comes to glitches in the news image as seen below. Resizing the window over a certain point fixes it again, but until I do that it stays this way - also applies to the other images that follow.

![grafik](https://user-images.githubusercontent.com/40496/214274034-02369465-fd8f-4675-8349-0262ddaedfa9.png)

**Comment by gtalha07** [comment]
It is because of flag we have set ```debugInvertOversizedImages = true``` and implies that we need to optimize the decoded image resolution as its taking more memory than expected.
