### ISSUE TITLE
```ChatListItem``` Text Overflow on mobile devices

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#473]
Text Overflow in message description of ```ChatListItem``` should be dealt with wrap.
![image](https://user-images.githubusercontent.com/68579938/216023182-35504d42-d92b-4f44-8be4-aba69c8722f5.png)

**Comment by kumarpalsinh25** [comment]
@gtalha07 
Can you provide more information to reproduce this issue?

**Comment by gnunicorn** [comment]
I think this has already been fixed in some previous update. Please report again if it reappears.
