### ISSUE TITLE
How to seft hosting acter ?

### ISSUE THREAD

**Issue by yodatak** [acterglobal/a3#561]
Hi im in a worker union and we try to have a tool like this that already use our matrix server 

It realy a nice project !

How to self install it ?

**Comment by gnunicorn** [comment]
Hi @yodatak ,

acter is still in heavy development and doesn't yet support actually being used, in particular it doesn't have any web-ui to host yet. As for servers, we are trying to stay as close to the federated matrix network as possible and hope to be able to work with any matrix server (or at least any reasonably configured synapse matrix server). For that our recommended way to setup a matrix server on your own instance is to use [the matrix ansible docker deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)-toolkit. This is how we configure our server, too. We are hoping to offer turn-key solutions that are less technical at a later stage, too.

To stay up to date, I recommend following the [news matrix channel](https://matrix.to/#/#news:acter.global)
