### ISSUE TITLE
nightly crashes from 2nd start forwards

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#563]
since [#7bb57c47a83453e37c7ad55851fc3f62ef6bfe58](https://github.com/acterglobal/a3/commit/7bb57c47a83453e37c7ad55851fc3f62ef6bfe58) the nightly build crashes on startup on linux and windows with a memory explosion. Whether using the rust in release or not doesn't seem to matter, only that it was build as a `flutter bundle` before.

**Comment by bitfriend** [comment]
In windows, 1st launch doesn't occur crash, but 2nd launch occurs crash.

**Comment by gnunicorn** [comment]
I can add that 
a) it also crashes the same way with `flutter run --release` and `flutter run --profile`
b) it crashes before the memory service can even attach to the app
c) it seems to be working _some_ times if there is no internet connection - still crashes more often than it doesn't...
