### ISSUE TITLE
windows nightly build fails

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#569]
last one ths worked is https://github.com/acterglobal/a3/releases/tag/nightly-2023-03-16

**Comment by bitfriend** [comment]
I launched app as profile mode (rust was debug build) in vs code on windows.
It opened, but when I clicked `OceanKAN` space in navigation rail, app crashed with error msg `[2023-06-10][00:19:02][panic][ERROR] thread '<unnamed>' panicked at 'capacity overflow': library\alloc\src\raw_vec.rs:525`.
This error looks like rust error.

**Comment by bitfriend** [comment]
I think memory analyze about flutter side is needed.

**Comment by bitfriend** [comment]
Fixed by https://github.com/acterglobal/a3/pull/649.
But it is not perfect and we will replace `ffi-gen` with `uniffi-dart` to solve this issue perfectly.
