### ISSUE TITLE
Fix the display name and avatars from Profile APIs

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#647]
The display name and avatars are appearing as of same instance against all user ids, and we can see those results in sections where it is rendered and from these debug logs:
<img width="1359" alt="Screenshot 2023-06-17 at 1 23 29 AM" src="https://github.com/acterglobal/a3/assets/68579938/95ccc6a5-070d-45d9-9d10-ee74f3d88080">

**Comment by gnunicorn** [comment]
fixed in #660
