### ISSUE TITLE
GCC issue in android release build on windows platform

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#657]
We have to remove `-Zbuild-std` from release build command because tree shaking destroys release sync callback.
On macos, it is possible to remove it, but not on windows.
On windows, android studio emulator (x86_64) cannot load `libacter.so` and outputs the following msg.
`Failed to load dynamic library 'libacter.so': dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/global.acter.a3-1/lib/x86_64/libacter.so"...`

**Comment by gnunicorn** [comment]
outdated.
