### ISSUE TITLE
hamburger icon has too low resolution 

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#66]
On high res screens, the hamburger icon appears pixelated (while the other icons are sharp as wanted):

![Uploading Screenshot_20220424-202003.png…]()

We must replace the current asset with a high res - ideally SVG - version.

**Comment by gtalha07** [comment]
Can replace with SVG provided in Figma design in next commit.

**Comment by gtalha07** [comment]
Fixed in latest commit of PR #60. Closing now.
