### ISSUE TITLE
dashboard title capped

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#671]
On mobile you can't even read the dashboard title as it is capped long before running out of space...

![Screenshot_20230627-110754](https://github.com/acterglobal/a3/assets/40496/240e01fa-4edb-4eef-9878-21bfad05d1ea)

**Comment by gtalha07** [comment]
@gnunicorn Can you confirm if this is fixed ? It should preview `Overview` instead of `Dashboard` string in mobile version.

**Comment by gnunicorn** [comment]
jup, fine on latest nightly.
