### ISSUE TITLE
fallback avatar too small

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#672]
Observable at least in the space overview: the fallback avatar is rendered a lot smaller than the others.

![Screenshot_20230627-110855](https://github.com/acterglobal/a3/assets/40496/f7423d97-17b3-49b5-bc58-63552c09c1b5)

**Comment by gnunicorn** [comment]
still a problem, reopening.

**Comment by gtalha07** [comment]
Closing as fixed in #1149.
