### ISSUE TITLE
pin overflows

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#689]
Pins overview overlap issues on mobile:

![Screenshot_20230702-104517](https://github.com/acterglobal/a3/assets/40496/66028931-edc9-4234-92da-37b13665485b)

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Is this issue is still persists? Can you check and confirm?

**Comment by gnunicorn** [comment]
this has been addressed, but is still an issue on very small screens:

![grafik](https://github.com/acterglobal/a3/assets/40496/619410ea-2c14-4844-a4e5-2e06bfd29360)
