### ISSUE TITLE
pin creation space field ui bugs

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#690]
Select 'parent space' wrong name in pin creation
![Screenshot_20230702-104557](https://github.com/acterglobal/a3/assets/40496/a2da3207-0796-4b0f-87de-b4de13168ab9)

And once selected, if the space name is long, the field label is squashed: 
![Screenshot_20230702-104612](https://github.com/acterglobal/a3/assets/40496/5ec68c8f-906b-40ee-8093-4fc0fb161f56)

And it allows selecting spaces we aren't allowed to post pins in...

**Comment by kokodavid** [comment]
@gnunicorn 'Select 'parent space' wrong name in pin creation' kindly clarify on what it should be .

**Comment by gnunicorn** [comment]
@kokodavid well, if you select the space, the title is "select parent space", while it should just be "select space".

**Comment by kokodavid** [comment]
@gnunicorn I changed the alignment that existed before and it now looks like this.
![image](https://github.com/acterglobal/a3/assets/47295684/0fdfc42a-ce59-41aa-8912-de986939fce4)
![image](https://github.com/acterglobal/a3/assets/47295684/20db2b70-4da0-4e0b-a6a3-b197447ad746)
![image](https://github.com/acterglobal/a3/assets/47295684/f62dd6f8-9384-4fd3-8dc8-56a13695f7ef)
