### ISSUE TITLE
mobile space overview overflow

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#692]
Can't see the thing on the bottom

![Screenshot_20230702-104815](https://github.com/acterglobal/a3/assets/40496/2f621629-d2c4-4f57-be0d-870b0f5a3342)

**Comment by gtalha07** [comment]
Seems like ```ShellRoute``` child height isn't exactly what it is as inherited from parent and scrolling only goes upto the height of parent. What we would need is setting dynamic height but its nearly impossible as overview card sizes vary according to their content. Applied fix in #700  as to give more height in mobile view than parent.

**Comment by gnunicorn** [comment]
how about just adding a padding on the bottom inside of roughly the height of the bottombar? Sounds like an okay-ish workaround to me.
