### ISSUE TITLE
Quickjump search shouldn't be case-sensitive

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#693]
Currently, typing `ocean`, the `OceanKan` project doesn't show up:

![grafik](https://github.com/acterglobal/a3/assets/40496/09d6d6cf-cf35-495a-9061-6c029f77ddf6)

**Comment by kokodavid** [comment]
@gnunicorn 
![image](https://github.com/acterglobal/a3/assets/47295684/1039bc3f-ec0b-46cd-8111-0304f0f646c0)

**Comment by gnunicorn** [comment]
@kokodavid looks good. not clear why the PR #779 is linked to it though...
