### ISSUE TITLE
Input field text alignment out of whack

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#741]
On pin and news, the text field alignment is center, rather than top left as you'd expect.
![grafik](https://github.com/acterglobal/a3/assets/40496/6ffb309a-ad5b-48de-ab38-1b3577e66f05)

**Comment by kokodavid** [comment]
@gnunicorn I am trying to fix this issue but I can't see the content section , was it removed ?
![image](https://github.com/acterglobal/a3/assets/47295684/9fbe99a8-f75a-4ad5-9764-aa2df61abea3)

**Comment by kokodavid** [comment]
@gnunicorn I have fixed this issue .

**Comment by gnunicorn** [comment]
@kokodavid can you link the PR and close the issue then?
