### ISSUE TITLE
Creation sheets

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#747]
news, pins, etc: make CTA buttom for post the highlighted one, not the cancel.

**Comment by kokodavid** [comment]
@gnunicorn I hope this is what you meant .
![image](https://github.com/acterglobal/a3/assets/47295684/2689db70-12cb-4c01-a1a6-c3a667077a39)
![image](https://github.com/acterglobal/a3/assets/47295684/43c19ef1-2509-4901-9ead-6afe12f5082f)
![image](https://github.com/acterglobal/a3/assets/47295684/bd5edf11-a73b-400c-b037-77a20e23e8c2)
