### ISSUE TITLE
Layout issue about single line msg

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#766]
Now we have layout issue as following.
![image](https://github.com/acterglobal/a3/assets/48786056/79487842-1b98-46ac-ab55-3f9956167018)

**Comment by kumarpalsinh25** [comment]
@bitfriend  
Is this issue is still persists? Can you check and confirm?

**Comment by bitfriend** [comment]
I guess it occurred because `@talha:effektio.org` overflowed its placeholder.
Now I can't reproduce this issue.
It seems to be fixed.
