### ISSUE TITLE
Clean up custom form fields in onboarding

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#781]
We currently have super customised Input fields for the onboarding forms in Login and Registration, but they lack certain features. We should replace them with [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html) and use the default material3 features.

**Comment by kokodavid** [comment]
@gnunicorn I need a bit of clarification on this issue , Should I replace the LoginTextField with TextFormField instead ?
![image](https://github.com/acterglobal/a3/assets/47295684/952dfa7f-5dd0-4b47-8957-03c628ff39ad)

**Comment by gnunicorn** [comment]
Yes, exactly. We have some custom LoginTextFields in this and some RegistrationTextFields in the registration page with slightly custom behaviour. It was an attempt to implement the specific design at the time, but things have progressed and the regular TextFormField are much better at handling all these states and others today (like moving the text-field name above once you start typing, which is a often complained issue). We basically want to replace all custom TextFields in the app with the regular TextFormFields and this PR is about replacing them in the onboarding feature :) .

(also less custom widgets and code to maintain).
