### ISSUE TITLE
Add session review into activities section

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#789]
analogous to the invitations, I'd be great if we had a big card on the top of the activities screen when there are unverified sessions, with an easy way to start the verification process. Particularly needed when the first progress didn't succeed.

**Comment by bitfriend** [comment]
Currently the cross-signing only shows up once, but if then it doesn't happen, there is no way to re/start it after.

And @gnunicorn was thinking that we should probably move that popup + starting the process into the activities-section, analogous to the way it works with invites: as long as there are unverified sessions, there should be a card on the top that allows you to review all connected sessions and either start a verification process or kick the session (similar to the sessions-panel here in element).

I will clone session panel of element app to activities section.

**Comment by bitfriend** [comment]
@gnunicorn brought up the following logic:
- a sub-settings space listing all sessions, with unverified on the top of the list, order behind in since_last_seen.
- when there are exactly one unverified session, we show that entry right there in the activities tab on the top and allow immediately to start the process
- if we have more than one unverfieid session we only show a general "You have X unverified sessions log in" with a button "review" that goes to that newly created page from which the user can interact with them

**Comment by bitfriend** [comment]
Now app doesn't accept `KeyVerificationReady` event.
I must continue to implement that event handling in next PR.
