### ISSUE TITLE
Empty space fillers (for mobile and desktop)

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#797]
Add hyperlinks in the empty states to encourage an action + make the empty states more descriptive/visual - [Design’s here](https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=5173-76889&mode=design&t=zDpeGVD4G3OFML1f-4).

Most notably:
 - [x] Overall:
     - [x] Replace Empty-Update on home with something
     - [x] Explainer for pins (switch to the same layout as the activities-section)
 - [x] Within Space
    - [x] No Spaces
    - [x] No Events
    - [x] No Chats
 - [x] Within User
    - [x] No chats
    - [x] No activities 

 

Note: depending on the permissions the user _might_ not be able to do anything in a specific section. In which case we should make clear that their admins can and they need to talk to them if they want to have access to it.

Inspiration:
![e04052bb-2051-4807-9748-c8be721ab0dd-cover](https://github.com/acterglobal/a3/assets/77483554/3f63e3bb-5a3d-4769-bf73-9d2630fa0b91)

**Comment by emilvincentz** [comment]
Jules has now given feedback.
Next step: To discuss the flow with @MirekKolaja

**Comment by MirekKolaja** [comment]
@emilvincentz, @kokodavid - I am gonna take over this task since it is directly linked to the onboarding experience which I have been recently working on.

**Comment by MirekKolaja** [comment]
The designs for the empty states can be found [here](https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=9177-7471&mode=design&t=zmfx2wzXSJQeyQuC-4)

**Comment by emilvincentz** [comment]
great work @MirekKolaja and team! 
think it looks awesome.
Only added a few comments

**Comment by MirekKolaja** [comment]
Thanks for the comments, @emilvincentz. I implemented the changes for what you mentioned. 

Made sense with the internal organizing focused + the frequent users notification screens weren't considered since this is for the onboarding of the new users but I made a design for it, so we have that scenario covered now.
