### ISSUE TITLE
Clean up chat names

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#798]
Chat should everywhere be called "chat", not "group chat" or "group" or "room", just "chat". Check and replace on:
 - [x] chat creation process
 - [x] spaces -> chats
 - [x] chats overview -> chat room -> chat room details

Example:
<img width="1000" alt="Screenshot_2023-07-24_at_13 25 54" src="https://github.com/acterglobal/a3/assets/40496/3eb17725-801e-4558-b08c-8431b1f2530a">

**Comment by kokodavid** [comment]
@gnunicorn I hope the last screenshot solves task number 3.
![image](https://github.com/acterglobal/a3/assets/47295684/cfaccc67-4d3d-463c-b610-8eeca60a817a)
![image](https://github.com/acterglobal/a3/assets/47295684/79407a72-a4b8-49f0-891d-bfb34019d051)
