### ISSUE TITLE
more-actions button in profile not visible

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#801]
maybe some color setting or something:

![image](https://github.com/acterglobal/a3/assets/40496/7bcdca8c-2bcc-445c-9b30-63f313d2b937)

**Comment by kokodavid** [comment]
![image](https://github.com/acterglobal/a3/assets/47295684/91593e43-7c0a-463b-b21d-1f169498b168)

**Comment by gnunicorn** [comment]
@kokodavid where are you putting the code? Better to have these on the PR and just link the issue...

**Comment by kokodavid** [comment]
Noted , I will do that from now going forward. I haven't pushed the code because I am waiting on clarification on this issue (https://github.com/acterglobal/a3/issues/802) before I can raise a pr for the issues I have worked on .
