### ISSUE TITLE
Clean up "my profile" page

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#802]
It contains a bunch of dead tabs with no real value right now. For the time being, just replace it with a centralised button menu to go to: Edit Profile, Settings.

**Comment by kokodavid** [comment]
@gnunicorn 
I am trying to understand the suggestion about replacing the tabs with a centralized button menu to be used for Edit Profile and Settings. Is this what you mean ?

![image](https://github.com/acterglobal/a3/assets/47295684/c6c50aa9-f282-4efd-a631-1f130b4b1eb5)

**Comment by gnunicorn** [comment]
@kokodavid yeah, something like that. I am not sure, what else we can put here without too much work ...
