### ISSUE TITLE
Several smaller chat issues

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#804]
1. routing to the chats-tab the first time, we see:
  ![image(2)](https://github.com/acterglobal/a3/assets/40496/1ec2ca71-be61-465d-b5ff-809cde36c9c4)
  ```
  [2023-07-28][17:46:30][acter_core::store][TRACE] saving user=Some("@emil-oceankan-exmpl:acter.global") key="$ED8KUT2PivLC7HHrd2_dvxzBgm6t7-b35GBOlTI4TgA"
  [2023-07-28][17:46:43][acter::platform::native][ERROR] Bad state: called ProviderSubscription.read on a subscription that was closed
  [2023-07-28][17:46:43][acter::platform::native][ERROR] #0      _ExternalProviderSubscription.read
  provider_base.dart:173
  #1      ConsumerStatefulElement.watch
  consumer.dart:564
  #2      _DashboardState._checkIfSpacesPresent.<anonymous closure>
  dashboard.dart:39
  #3      SchedulerBinding._invokeFrameCallback
  binding.dart:1284
  #4      SchedulerBinding.handleDrawFrame
  binding.dart:1223
  #5      SchedulerBinding._handleDrawFrame
  binding.dart:1072
  #6      _invoke (dart:ui/hooks.dart:142:13)
  #7      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
  #8      _drawFrame (dart:ui/hooks.dart:112:31)
  flutter: Acter Conversations Stream 
  ```

2. entering the room `ben, emilvincents` in the chat as `emilio`, I am getting parsing failures:

![image(1)](https://github.com/acterglobal/a3/assets/40496/7318aa02-8257-476d-b74d-15ab6708fcba)

**Comment by gtalha07** [comment]
The first exception ```Bad state: called ProviderSubscription.read on a subscription that was closed``` doesn't relate with chats only, it happens when switching to any tab during sync process...

**Comment by gtalha07** [comment]
Closing as per #809. The first exception will be filed as separate issue as its related with sync state.
