### ISSUE TITLE
chat empty during initial load

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#805]
Navigating to the chats section shows an empty screen after starting up while the app still syncs - which for my account is easily exceeding. 100 secs. We should instead show the cached data...

![Screenshot_20230731-010300](https://github.com/acterglobal/a3/assets/40496/a2bb6e86-cbea-4212-af4c-cd83a8539aeb)

**Comment by gtalha07** [comment]
The problem lies in ```ConvosRx()``` emitting empty list initially (in case of rooms). This should be prevented because we also want to check if indeed client is not part of any chat rooms.

**Comment by gtalha07** [comment]
Also would be handy if we just emit ```Convo``` rather than ```List<Convo>```.
<img width="697" alt="Screenshot 2023-07-31 at 6 04 19 PM" src="https://github.com/acterglobal/a3/assets/68579938/e70f49a9-5b96-43e0-b1fd-94c50e0aa279">

**Comment by gtalha07** [comment]
Closing as per #809. The chat should preview loading statement while the sync is still in process and chats when it completes.
