### ISSUE TITLE
Spaces and chats are mixed up

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#808]
Starting up and registering our newly created spaces are sometimes showing up in the chats-area.

**Comment by gnunicorn** [comment]
It's unclear when and how that happens :( ... If anyone has steps to reproduce it, that'd be great.

**Comment by emilvincentz** [comment]
just tested a couple of times and seems to no longer be the case. Maybe the refactoring of the chat helped

**Comment by gnunicorn** [comment]
okay, closing as non-reproducible for now. please reopen if this happens to you (again).
