### ISSUE TITLE
Reactivate typing feature.

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#811]
Now we have somewhat migrated the chat infrastructure to riverpod state handlers, we should extend it to typing state and UI handlers.

**Comment by gnunicorn** [comment]
As far as I can tell, we are already _sending_ that event again, but it seems we have no way of showing it in the Acter UI. Also, we should have a system-wide and specific-chat-setting to allow to disable sending the typing notification.

**Comment by gtalha07** [comment]
Precisely, we do have customised typing widget already written in chat module, just need to glue with typing stream api.
