### ISSUE TITLE
Chat: check permissions to sent

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#820]
Currently room permissions are missing for members which would present the room UI in different ways. Like ability to post events, encryption status, power level. 
<img width="1010" alt="Screenshot 2023-08-02 at 10 01 01 PM" src="https://github.com/acterglobal/a3/assets/68579938/5bb0dcbc-87ee-4460-b58f-0d904bf7d3f3">

**Comment by gnunicorn** [comment]
Let's make this more precise:
We aren't checking whether you have the permission to send regular text messages but always show the text-bar. that is confusing as messages are also not appearing.
