### ISSUE TITLE
Finalize pins section

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#825]
With Bens comment below, we should:

- [ ] Align on what is a pin? (Currently users can only create pins that is text or links, what about files?)
- [ ] Finalise the designs for both mobile and desktop (How to: Edit, Read, Update, Delete)

Current Designs:
https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=4178-71815&mode=design&t=EmRT9iiNlFKgdXGq-4

**Comment by gnunicorn** [comment]
I never had time to go through the design here, but from the feedback we have also gotten, considering Pins to be of a specific type (Link vs Text vs File vs Image) doesn't really make sense. I'd rather argue, we want them to allow a Link, a Text and any number of attachments. That's also how the underlying matrix events are currently set up and thus mainly need a UI to be added.

**Comment by emilvincentz** [comment]
dont fully understand the difference between the two, but I trust that what you write makes sense and aligns with the user feedback so far. 
Maybe go over it on Monday with the design team? especially if the back-end is already set up and ready to go
