### ISSUE TITLE
Expand text input field when typing messages

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#836]
When typing longer messages on desktop, the text input gets too small, making it difficult to go back and edit.

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/f957f4f5-9177-4273-8c88-7195bd6692f1)

**Comment by kokodavid** [comment]
Fixed
![image](https://github.com/acterglobal/a3/assets/47295684/a367d180-9f39-41ff-89a5-c43996f80b55)
