### ISSUE TITLE
Implement create chat flow

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#853]
Direct Message Flow:
- [x] Update "create chat screen"
- [x] Implement DM flow

Channel / Group chat 
- [x] Update create form
- [x] Implement "invite members" section
- [x] Implement empty state in the chat 

Designs:
https://www.figma.com/file/ps6Wa0fuRYkKNjPPaZqVaO/Acter-3.0---Design?type=design&node-id=6188-65861&mode=design&t=vJd84evv2R2E3Vr9-4

Why important:
- Currently not able to create a Direct message, without having to go through the steps of naming the conversation. 
- We want to make it easier for people to invite other people / spaces to a conversation.
-

**Comment by emilvincentz** [comment]
Mirek and David to approve final designs:

- [ ] Design for Mobile and Desktop
- [ ] Ensure correct labelling 
- [ ] Ensure correct icons

**Comment by emilvincentz** [comment]
@MirekKolaja when you have reviewed /updates this one, can you let me know? 
Then we can move it over to Talha, so he can get started on it 🙏

**Comment by MirekKolaja** [comment]
Sure @emilvincentz , I will tag you when there will be an update 😉
