### ISSUE TITLE
Design: fatal errors and recoverable mistakes

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#872]
How do we display:

- [ ]  Errors in Rust and Flutter, that we can’t recover from
- [ ]  Fatal Problems in the underlying system
- [ ]  User has been logged out
- [ ]  Permissions have been denied

**Comment by emilvincentz** [comment]
is this related? 
https://github.com/orgs/acterglobal/projects/3/views/7?visibleFields=%5B%22Title%22%2C%22Repository%22%2C%22Assignees%22%2C%22Status%22%2C46698199%2C51809158%2C39698372%2C%22Milestone%22%5D&pane=issue&itemId=28794339

**Comment by gnunicorn** [comment]
already done.
