### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#877]
We need to upgrade the onboarding process to:
 - [x] #920
 - [x] https://github.com/acterglobal/a3/issues/919
 - [x] #921
 - [x] #1446

**Comment by gnunicorn** [comment]
new flow for that in [#1445](https://github.com/acterglobal/a3/issues/1445)

**Comment by gnunicorn** [comment]
api in progress https://github.com/acterglobal/a3/pull/1638/files
