### ISSUE TITLE
user deactivation

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#892]
As we allow for users to register, by the rules of Apples AppStore the user must also be able to delete the account (data):

> Guideline 5.1.1(v) - Data Collection and Storage

> We noticed that your app supports account creation but does not appear to include an option to initiate account deletion.

> Apps that support account creation must also offer account deletion to give App Store users more control of the data they've shared while using your app.

> Next Steps

> If your app already supports account deletion, reply to this message and let us know how to locate this feature. If your app does not support account deletion, revise your app to include an option to initiate account deletion and delete all user data you are not legally required to retain.

> If you are unable to offer account deletion or need to provide additional customer service flows to facilitate and confirm account deletion, either because your app operates in a highly-regulated industry or for some other reason, reply to this message in App Store Connect and provide additional information or documentation. If you have questions regarding your legal obligations, check with your legal counsel.

> Keep these requirements in mind when updating your app to support account deletion:

> - Only offering to temporarily deactivate or disable an account is insufficient.
> - If users need to visit a website to finish deleting their account, include a link directly to the page on your website where they can complete the process.
> - You may include confirmation steps to prevent users from accidentally deleting their account. However, only apps in highly-regulated industries may require users to use customer service resources, such as making a phone call or sending an email, to complete account deletion.

---

However, matrix itself doesn't really support user deletion. We might want to do what the element-web version does though: remove all personal information, drop out of all spaces and rooms, remove all devices/sessions and put an impossible password on the account. That could do well enough and would block the user-id for the time being. Might be sufficient.

**Comment by bitfriend** [comment]
Yeah, it looks promising to follow the precedent of element app.

**Comment by gnunicorn** [comment]
Looks like searching for the right term, finally yielded a result. As we can't delete, we can [`deactivate`](https://docs.rs/matrix-sdk/latest/matrix_sdk/struct.Account.html#method.deactivate) though. We need to implement that behaviour and have a clear, large UI about it.
