### ISSUE TITLE
chat mixup bug

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#899]
Sometimes when i jump to another chat in the chat selector, it shows the conversations from another chat.
Although restarting the app, it sometimes still occur. 

In below image, it shows the chat content from my conversation with Ben. 

![Image](https://user-images.githubusercontent.com/77483554/264291215-5a6643b2-2ecf-490d-b44b-987ff1606ddc.png)

Maybe its related to this bug i suddenly encountered.
Goes away when reopening the app, but not sure whats triggers it.

![Image](https://user-images.githubusercontent.com/77483554/264291566-82e43cac-707d-445d-8adb-7aaf178992af.png)

**Comment by gnunicorn** [comment]
refs #905
