### ISSUE TITLE
Document flutter & rust best practices

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#910]
We have learned a few lessons using riverpod and flutter already, let's start documenting these - especially those that can not be enforced by lints - including a decent explanation as to why that matters. Like:

- avoiding `requireValue` and `ref.watch(clientProvider)!`
- general try-catches (rather use AsyncValues)
- router for state management
- proper dependency management (ref.watch rather than ref.read(someProvider.notifier).someFunction())`)

**Comment by gnunicorn** [comment]
Flutter responsive advices:
 - Use `MediaQuery` for sizes
 - for MaxValue use `BoxConstraints`
 - use `isDesktop` rarely! It is almost always misleading in terms showing something because of sizes available (always remember: the latest iPad touch has a higher resolution than the also supported MacBook Air 2017! - `isDesktop` is an inadequate approximation of what we actually want and that is responsiveness according to the available space)

**Comment by gnunicorn** [comment]
- Colors may not be hardcoded in the code, but should be pulled from the AppTheme.

**Comment by gnunicorn** [comment]
Rust as well:
 - no `unwrap` outside of test-code - use `expect` if you must
 - use `expect` to clarify _developer_ assumptions. e.g. unpacking an Option that the current code _ensures_ is filled or if the surrounding `if` is meant to ensure the assumption can't be broken.
 - use `?` and `bail!(...)` to verify any user input, don't `panic` / `expect` / `unwrap` on user based input. Ensure the
 - use `.context(...)?` on `Option`s only, and ensure you are giving a user understandale error message.

**Comment by bitfriend** [comment]
`?` is handling `Result<>`.
every time you have a `?`, it will effectively expand to:
```rs
let value = match value {
     Ok(v) -> v,
    Err(e) -> return Err(e))
};
```

**Comment by gnunicorn** [comment]
riverpod:
 - don't use setState (it almost always silently fails if we do) but pin to the provider
 - do as much calculation in the providers
 - be as specific as possible on the data from your provider, use `.select()` if you only need one parameter, to avoid unnecessary re-renders
 - provider chaining is good, use it!

**Comment by gnunicorn** [comment]
don't `requireValue!` but `valueOrNull?` always.

**Comment by gnunicorn** [comment]
flutter/dart general: `!` only if you checked for `!= null` pretty much right before.

**Comment by gnunicorn** [comment]
started draft here: https://ghost.acter.global/dev/code-style-best-practices/

**Comment by gnunicorn** [comment]
All documented here now: https://ghost.acter.global/dev/code-style-best-practices/
