### ISSUE TITLE
smaller UI glitches (on Android)

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#932]
As you can see:
- title is slightly cut off
- password reset should be on the bottom
- Login button should be wider (80-85% width in this screen)
- Pw reset doesn't do anything 

![Screenshot_20230912-161108](https://github.com/acterglobal/a3/assets/40496/b6e83da9-3bda-40b0-af48-9f839bd45dbb)

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
This is how current login screen looks like.
![Screenshot 2023-10-26 at 2 06 02 PM](https://github.com/acterglobal/a3/assets/51526480/201a600f-b026-416d-aa47-2775fe37e995)

- Apart from the "Login button should be wider (80-85% width in this screen)" issue, I don't see any other points.

**Comment by gnunicorn** [comment]
@kumarpalsinh25 the login button should still be expanded to reach 50-85% of the width of the form.

secondly, on Desktop this currently expands to the entire screen. While on it, let's put the content into a `Center` and Constrained box with a width of 500-600 or something decent ...
