### ISSUE TITLE
Chat bug in spaces chat

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#935]
Im able to view some of the top chats within the acter space, but can not scroll down or join any of the other chats that I havent already joined. I can only go into the foyer chat that i automatically joined when i signed up.

https://user-images.githubusercontent.com/77483554/267420441-b8fbd328-461c-426f-8f71-6656ef98c217.MP4

**Comment by gnunicorn** [comment]
We have refactored the entire chat section in #915 and the input state with #954 -- both are in latest nightly. Can you please try again, and if this sill appears, reopen this report?

**Comment by emilvincentz** [comment]
the scrolling issue is now fixed, however im still not able to join/enter of the other chats (except foyer) that im already part of. 
However when enter that chat, it shows up under the space, instead of opening the chat window in full screen.
see video

https://github.com/acterglobal/a3/assets/77483554/e794f7bd-14cb-4568-b5c7-8cc99c53af3a

**Comment by gnunicorn** [comment]
That's a different bug already part of https://github.com/acterglobal/a3/issues/955 . Quoting your report there.
