### ISSUE TITLE
chat creation bug

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#936]
When i create a chat from my home screen and click create, it:
1. shows a different chat.
2. most of the time doesnt show straight away in the chat overview.
3. If it shows and i click to enter it, it shows "failed to load messages due to some error occured loading room null check operatir used on the null value". 
If i restart the app, the chats shows succesfully (but after the chat overview page loading on average 15s).

Below 3 videos showing the different scenarios:

1. Wrong chat showing + not showing up in chat overview + succes when restarting:

https://user-images.githubusercontent.com/77483554/267424257-7d3ee190-aed3-47d9-8c08-bbc2d961698c.mov

2. Failed to load message

https://user-images.githubusercontent.com/77483554/267424852-cad0f3c4-5722-40e3-a693-371b50d892eb.mov

2. Dont know how to dublicate, but one time it showed a grey screen

https://user-images.githubusercontent.com/77483554/267422534-fc128e54-ba2d-43f5-9289-821be96856b4.mov

**Comment by gnunicorn** [comment]
We have refactorered the entire chat section in #915 and the input state with #954 -- both are in latest nightly. Can you please try again, and if this sill appears, reopen this report?

**Comment by emilvincentz** [comment]
look much better and chat is created instantly, 
However not able to validate all, as the "back arrow" no longer shows = I can not go back into the chat overview section.
https://github.com/acterglobal/a3/assets/77483554/acfd53d3-a193-40fa-918f-7278f0bf5c0e

**Comment by gnunicorn** [comment]
reported as a new bug.
