### ISSUE TITLE
Unverified session bug for new users

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#938]
new users have 2 unverified sessions, although they never signed in on other devices with that account

![Image](https://user-images.githubusercontent.com/77483554/267428142-bed30eff-ff3b-4a25-b183-81b3c7a29c41.png)

**Comment by gnunicorn** [comment]
let's retry a registration flow and whether that is still relevant.

**Comment by gnunicorn** [comment]
@emilvincentz just to confirm: this is created by registering a new account for the first time, right?! You immediately see two unverified sessions!?!

**Comment by emilvincentz** [comment]
@gnunicorn yep

**Comment by gnunicorn** [comment]
looks like I have a somewhat reliable test case for it!
