### ISSUE TITLE
objects from spaces a user has left, still shows

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#939]
all events, updates and pins from spaces a user has left, still shows for the user.

https://user-images.githubusercontent.com/77483554/267428875-32b56de1-c55c-4b9a-b0c8-3538067b6400.mov

**Comment by gnunicorn** [comment]
We have refactorered the entire chat section in #915 and the input state with #954 -- both are in latest nightly. Can you please try again, and if this sill appears, reopen this report?

**Comment by emilvincentz** [comment]
@gnunicorn they still appear unfortunately. 
They avatar no longer shows on the updates, but when clicked = shows error (see video below)
https://github.com/acterglobal/a3/assets/77483554/b4660e12-8232-49ff-a450-eaff92bcbb33

**Comment by emilvincentz** [comment]
yes, I can confirm at least with updates.

**Comment by gnunicorn** [comment]
also reported in https://github.com/acterglobal/a3-meta/issues/193
