### ISSUE TITLE
spaces appear in chat overview

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#942]
This was fixed, but just seemed to reoccur 

![Image](https://github.com/acterglobal/a3/assets/77483554/413db6f7-79db-4c20-82b6-8d4b6d2f339a)

**Comment by gnunicorn** [comment]
We have refactorered the entire chat section in #915 and the input state with #954 -- both are in latest nightly. Can you please try again, and if this sill appears, reopen this report?
