### ISSUE TITLE
Add "+" icon to "my spaces" header on home screen

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#944]
As new users now automatically join a space (Acter.global + Sandbox) they no longer get prompted with the "create space" pop up. Thats why i think its important that we either 

1. add the + icon to "my spaces" header on home screen
2. or, make it more clear that the "my spaces" is clickable.

Personally i would go for nr.1 as it doesnt take up a lot of space and its the shortest click path

![Image](https://user-images.githubusercontent.com/77483554/267912238-48c4fc1d-0b38-42d1-b3cc-54acdc8b0941.png)

If its not a big job, adding the + icon in the space menu on desktop (like element) would also make it easier for users to get started with creating their own space.

![Image](https://user-images.githubusercontent.com/77483554/267913584-47954ee3-a846-48f0-9e00-2ff5c15b5cfb.png)

**Comment by gnunicorn** [comment]
Should that directly go to "create a space" or open a popup to "create or join"?


I am not super convinced about the idea of adding very permanent icons for an activity that is rarely used... What makes more sense is that if there is only very few items in the MySpaces-Section (less than 5) we add a button on the bottom to "Create or Join Space".

**Comment by emilvincentz** [comment]
Im up for that as well, as long as its easy for first time users to know where they can create/join a space

**Comment by gnunicorn** [comment]
move spaces listing to the top of the dashboard.

**Comment by gtalha07** [comment]
@gnunicorn Is this feasible?
<img width="523" alt="Screenshot 2023-09-18 at 10 51 13 PM" src="https://github.com/acterglobal/a3/assets/68579938/009459b5-4e90-44b0-84f3-ea85486983c9">

**Comment by gnunicorn** [comment]
yeah, sure.
