### ISSUE TITLE
Live-redactions are not applied

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#947]
Following #943 , if I redact any content (Pin, NewsEntry or Event), this will not remove them from the local view because:
 - [ ] a redaction that comes down live (rather than a redacted event) is currently not applied to the executor 
 - [ ] the executor does not issue a refresh of the corresponding UI component.

This unfortunately means that the user redacting the content will ignore the existing redaction issued and because we only sync new events never learns about the redaction. As well as anyone currently online, as their caches are not refreshed and the update not applied until they fresh-sync...

**Comment by emilvincentz** [comment]
![image](https://github.com/acterglobal/a3/assets/77483554/2b534ad6-99dc-4cba-84f2-09b70f686063)
