### ISSUE TITLE
Improve "invite members to space/chat" flow

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#949]
https://balsamiq.cloud/sj2u1jx/plw5law/r18F4

PART-1:
![Image](https://github.com/acterglobal/a3/assets/51526480/e5470511-72e7-4ba5-88c0-0f0e6a7b1703)

PART-2:
![Image](https://github.com/acterglobal/a3/assets/51526480/fdf450c6-6b7f-46f2-9db9-9388a7ded738)

PART-3:
![Image](https://github.com/acterglobal/a3/assets/51526480/880f6b5d-afbc-45a6-ae2b-a42ffd6ac485)

![Image](https://github.com/acterglobal/a3/assets/51526480/ad0bf829-40d7-416c-aeec-60b57f540cdb)

[Invite-Flow.pdf](https://github.com/acterglobal/a3/files/15303549/Invite-Flow.pdf)

**Comment by gnunicorn** [comment]
> Adding "invite to" button on space overview page

Show it until we have reached more than 100ppl

**Comment by emilvincentz** [comment]
Currently when inviting members to spaces/chats, it takes some time to select the right spaces and chats, as it all just is one long lost, or actually two lists divided (spaces and chats)
A suggestion would be to cluster them together, as often you want to create an invite link where you select a space and a set of chats and subspaces. Similiar to element, although i think can make the UI even more clear. 


![Image](https://github.com/acterglobal/a3/assets/77483554/9b29cd64-3293-4a9a-82d9-896cbac43653)

**Comment by gnunicorn** [comment]
@kumarpalsinh25 finished the iteration 1.
