### ISSUE TITLE
Layout bug in reaction icon list

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#953]
On desktop build, I found layout bug in reaction icon list.
You can see it by long press of any message entry in chat room.
This is screenshot.
![image](https://github.com/acterglobal/a3/assets/48786056/59a3d5b8-7644-4ee3-bb68-45ac176767e6)

**Comment by kumarpalsinh25** [comment]
@bitfriend 
Is this issue is still exist? I'm not able to reproduce this.
