### ISSUE TITLE
When creating/updating pin, there is no “back” icon.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#959]

**Comment by gnunicorn** [comment]
How did you create it? Where should it be going back to?

**Comment by emilvincentz** [comment]
ahh I see what you mean.
Well in this case I was creating it from the Acter.global space.
If we dont want to add the back arrow, then we should make the acter.global space icon clickable

**Comment by gnunicorn** [comment]
> ahh I see what you mean.
>  Well in this case I was creating it from the Acter.global space.

Okay. Yeah routing back there makes sense. Looks like we are using a `context.go` where we should be using a `push`...

**Comment by gnunicorn** [comment]
fixed in #998
