### ISSUE TITLE
Hide menu bottom menu (on mobile) when in the chat and keyboard is showing

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#961]

**Comment by emilvincentz** [comment]
Right now the menu takes up signifact space.
I propose to hide the menu as long as the user is typing, not only in chat section but anywhere.


![Image](https://github.com/acterglobal/a3/assets/77483554/082bab9b-8753-4f93-be8d-9a253b9c079f)

**Comment by gtalha07** [comment]
@emilvincentz I don't think hiding a menu would do any better, it doesn't accumulate much height. What's more suitable is to resize the components, their text factor based on screen resolution, something which [sizer](https://pub.dev/packages/sizer) package would do.

**Comment by emilvincentz** [comment]
@gnunicorn @gtalha07 hiding the mean would give considerable extra space. 
Like how @kokodavid has made the designs,  people will use the back button to access the chat over and where the menu will show again. 
compared to the pain of having the menu showing and thereby limiting the chat view vs. the gain of hiding it while I a chat convo, I really don't see why we would have the menu in there taking up precious space.

Whatsapp, signal etc. does this as well.
<img width="300" alt="Screenshot 2023-09-21 at 11 32 16" src="https://github.com/acterglobal/a3/assets/77483554/69498d47-2a38-4b50-8c16-feca0f6b0c7d">

<img width="274" alt="Screenshot 2023-09-21 at 11 32 33" src="https://github.com/acterglobal/a3/assets/77483554/a9767921-d285-4d05-8eb5-393305b1e1b0">
