### ISSUE TITLE
hide ```emoji_picker_widget``` for chat input (mobile)

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#963]
Acter mobile versions show emoji icon for emoji input in chat textfield which deems unnecessary as touch keyboard supports it and also takes significant amount of space in chat ui. This should be hidden completely. 

<img width="970" alt="Screenshot 2023-09-18 at 3 19 39 PM" src="https://github.com/acterglobal/a3/assets/68579938/45121fff-26e5-437d-80de-1ef7e524e0b1">

**Comment by gnunicorn** [comment]
>  as touch keyboard supports it 

how confident are we that this is a true statement for all supported platforms? After all, all of Signal, WhatsApp and Telegram show it even on my rather modern device... ..

**Comment by gtalha07** [comment]
> > as touch keyboard supports it
> 
> how confident are we that this is a true statement for all supported platforms? After all, all of Signal, WhatsApp and Telegram show it even on my rather modern device... I'd stay on the side of caution here and argue we should keep it for the time being (and it really isn't that much space, even on a small device...).

True, not quite the strong feeling. I guess maybe I have to research over this in terms of how flutter handles it, and will share my opinion.

**Comment by gnunicorn** [comment]
@gtalha07 we can hide the bottom bar checking for [`viewInsets`](https://api.flutter.dev/flutter/widgets/MediaQueryData/viewInsets.html) .. I think that is reasonable...
