### ISSUE TITLE
cache chat images and optimisation.

### ISSUE THREAD

**Issue by gtalha07** [acterglobal/a3#964]
Chat Image messages aren't cached and gets a re-render on scrolling. Moreover, images decoded size should be optimised for chat feature as performance aspect.

**Comment by gtalha07** [comment]
Aside from render optimisation, images also throw exceptions sometimes which is bad behaviour :
<img width="1070" alt="Screenshot 2023-09-18 at 4 31 50 PM" src="https://github.com/acterglobal/a3/assets/68579938/62b5fbac-8247-4806-bb09-c0b922aedb19">
Eventually we want to figure out entirely how the image messages behaves in terms of matrix handling .i.e. showing blank placeholder if the image is in process of loading, and showing a retry option if its unsuccessful.

**Comment by emilvincentz** [comment]
also experiecning this frequently 
![Image](https://github.com/acterglobal/a3/assets/77483554/f7b02733-d240-4072-9fa2-a6a9181eaca9)

**Comment by emilvincentz** [comment]
I guess this loading issue is connected to this issue?


https://github.com/acterglobal/a3/assets/77483554/91f564cf-a1bd-47d6-a9f3-253b9313de93
