### ISSUE TITLE
Adding "invite to" button on space overview page

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#965]
Showing the invite button in the space until we have reached == users/invited...

**Comment by gtalha07** [comment]
We are already showing `invite users` in pop up menu of space overview. Does it mean we should move this to shell directly? Or also add invite button besides??
<img width="1612" alt="Screenshot 2023-09-20 at 6 13 14 PM" src="https://github.com/acterglobal/a3/assets/68579938/c9602a75-d356-4c92-a26e-ab745b22ce66">

**Comment by gnunicorn** [comment]
Yeah, directly in the "About"-Section of the space to make it more prominent.... there is a figma (I can't reach right now) showing it.
