### ISSUE TITLE
Various UI glitches

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#983]
UI broken stuff & fixes on IOS mobile -- feedback from matrix summit & post people-power-conference:
- [x] Double naming in create space and create event screen
- [x] messed up text when searching public directory 
- [x] text falls out of widget boxes (for events and pins and spaces overvew)
- [x] Acter app info screen text mess up
- [x] Text mess up in header of activity screen
- [x] Log-in screen, has layout issues at the top
- [x] Change "redact" to "delete or remove" for pins, messages, events, updates (non tech users don't know "redact".
- [x] #1018 

Se screens below

**Comment by emilvincentz** [comment]
![Image](https://github.com/acterglobal/a3/assets/77483554/cf9fc3a5-6d10-41a3-84df-47f0bb086922)
![Image](https://github.com/acterglobal/a3/assets/77483554/650fafb1-d8f6-47ee-8d7c-994af7ab284a)
![Image](https://github.com/acterglobal/a3/assets/77483554/8dfe611d-ad1b-421a-9fcb-7331de34ed9b)
![Image](https://github.com/acterglobal/a3/assets/77483554/317aecf3-2650-4660-9756-0414c13e9ddc)
![Image](https://github.com/acterglobal/a3/assets/77483554/c7360892-6adf-454c-be2d-3b69706274a9)
![Image](https://github.com/acterglobal/a3/assets/77483554/523759e9-dfdb-4948-b21c-9675e07e7984)
![Image](https://github.com/acterglobal/a3/assets/77483554/b55914d8-b586-4671-a7b8-a3d0101e193b)
![Image](https://github.com/acterglobal/a3/assets/77483554/469c68a9-2e5c-4858-b817-810c3f6bb6a6)
![Image](https://github.com/acterglobal/a3/assets/77483554/4fca99d3-2677-4309-9058-3edfd3d0dde0)
![Image](https://github.com/acterglobal/a3/assets/77483554/df95ee8a-742f-44d9-aee7-ee5fffa2301f)
![Image](https://github.com/acterglobal/a3/assets/77483554/b5d83ace-7023-418a-813b-661703c018e4)

**Comment by gnunicorn** [comment]
maybe use sizes package?
