### ISSUE TITLE
Invite button to chat not showing in chat info

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#985]

**Comment by gnunicorn** [comment]
can you share a screenshot or be more precise which element you mean with "chat info"?

**Comment by emilvincentz** [comment]
<img width="538" alt="Screenshot 2023-09-25 at 11 05 39" src="https://github.com/acterglobal/a3/assets/77483554/6f069c87-3ac9-422f-b1f2-488c3ed048e4">
